// recipe1.js
export const recipe1 = [
  {
    name: "Aloo Paratha",
    ingredients: [
      "2 cups whole wheat flour",
      "1 potato, boiled and mashed",
      "1 onion, chopped",
      "1 teaspoon cumin seeds",
      "1 teaspoon garam masala",
      "Salt to taste",
      "Ghee or butter for cooking",
    ],
    steps: [
      "In a bowl, mix whole wheat flour and water to make a dough.",
      "In a separate bowl, mash the boiled potato and mix with onions, cumin seeds, garam masala, and salt.",
      "Divide the dough into small balls and roll them into circles.",
      "Place a spoonful of potato mixture in the center and seal it.",
      "Roll out again into a flat paratha.",
      "Cook on a hot tawa with ghee or butter until both sides are golden brown.",
    ],
    instructions:
      "A popular North Indian flatbread stuffed with spiced mashed potatoes.",
    image: "Aloo paratha.png",
  },
  {
    name: "Masala Dosa",
    ingredients: [
      "1 cup rice",
      "1/4 cup urad dal (split black gram)",
      "1/2 teaspoon cumin seeds",
      "1/2 teaspoon mustard seeds",
      "1 onion, finely chopped",
      "1 potato, boiled and mashed",
      "1/4 teaspoon turmeric powder",
      "2 green chilies, chopped",
      "Salt to taste",
      "Ghee for cooking",
    ],
    steps: [
      "Soak the rice and urad dal in water for 6 hours, then grind into a smooth batter.",
      "Let the batter ferment overnight.",
      "For the filling, heat oil in a pan, add mustard seeds, cumin seeds, and onions, and sauté.",
      "Add the boiled potato, turmeric powder, chilies, and salt. Cook for a few minutes.",
      "To make the dosa, heat a griddle, pour a ladle of batter, and spread it thin.",
      "Cook until crispy, then add the potato filling inside the dosa.",
      "Serve with coconut chutney and sambar.",
    ],
    instructions:
      "A South Indian dish made with crispy rice crepes filled with spiced potato filling.",
    image: "masala dosa.jpg",
  },
  {
    name: "Poha",
    ingredients: [
      "1 cup flattened rice (poha)",
      "1 onion, chopped",
      "1 potato, peeled and diced",
      "1 teaspoon mustard seeds",
      "1/2 teaspoon turmeric powder",
      "1 green chili, chopped",
      "Salt to taste",
      "Fresh coriander leaves for garnish",
      "Lemon juice",
    ],
    steps: [
      "Wash and drain the poha to remove excess water.",
      "Heat oil in a pan, add mustard seeds, and let them splutter.",
      "Add onions and potatoes and sauté until golden brown.",
      "Add turmeric powder, green chili, and salt, and cook for a few minutes.",
      "Add the poha and mix well, cooking for a few more minutes.",
      "Garnish with fresh coriander leaves and squeeze some lemon juice before serving.",
    ],
    instructions:
      "A light and savory breakfast dish made with flattened rice, turmeric, and vegetables.",
    image: "poha.jpg",
  },
  {
    name: "Idli",
    ingredients: [
      "1 cup rice",
      "1/4 cup urad dal (split black gram)",
      "1/2 teaspoon fenugreek seeds",
      "Salt to taste",
      "Water as needed",
    ],
    steps: [
      "Soak the rice, urad dal, and fenugreek seeds in water for 6 hours.",
      "Grind the soaked ingredients into a smooth batter, adding water as needed.",
      "Let the batter ferment overnight.",
      "Grease the idli molds and pour the batter into them.",
      "Steam for 10-15 minutes until the idlis are cooked.",
      "Serve with coconut chutney and sambar.",
    ],
    instructions:
      "A traditional South Indian steamed rice cake, served with chutney and sambar.",
    image: "idli.jpg",
  },
  {
    name: "Upma",
    ingredients: [
      "1 cup semolina (rava)",
      "1 tablespoon oil",
      "1/2 teaspoon mustard seeds",
      "1/2 teaspoon cumin seeds",
      "1 onion, chopped",
      "1 green chili, chopped",
      "1/4 cup peas",
      "1/4 cup chopped carrots",
      "Salt to taste",
      "2 cups water",
      "Fresh coriander leaves for garnish",
    ],
    steps: [
      "Heat oil in a pan, add mustard seeds and cumin seeds, and let them splutter.",
      "Add onions and green chili and sauté until onions are translucent.",
      "Add peas and carrots and cook for a few minutes.",
      "Add semolina and roast it until it turns golden brown.",
      "Slowly add water while stirring, to avoid lumps, and cook until the water is absorbed.",
      "Garnish with fresh coriander leaves and serve hot.",
    ],
    instructions:
      "A savory South Indian breakfast dish made with roasted semolina and vegetables.",
    image: "upma.jpg",
  },
  {
    name: "Chole Bhature",
    ingredients: [
      "1 cup chickpeas (chole), soaked overnight",
      "2 cups all-purpose flour (for bhature)",
      "1/4 cup yogurt",
      "1 teaspoon baking soda",
      "2 onions, chopped",
      "2 tomatoes, chopped",
      "1 tablespoon ginger-garlic paste",
      "2 teaspoons chole masala",
      "Salt to taste",
      "Oil for frying",
    ],
    steps: [
      "Boil the soaked chickpeas until soft.",
      "Heat oil in a pan, add onions, ginger-garlic paste, and sauté until golden.",
      "Add tomatoes and chole masala, and cook until tomatoes are soft.",
      "Add the boiled chickpeas and simmer for 10-15 minutes.",
      "To make bhature, mix flour, yogurt, baking soda, and water to form a dough.",
      "Roll out small balls of dough and deep fry until golden and puffy.",
      "Serve the hot bhature with chole.",
    ],
    instructions:
      "A popular North Indian dish consisting of spiced chickpeas served with fried bread.",
    image: "chole bhature.jpg",
  },
  {
    name: "Vada Pav",
    ingredients: [
      "4 pav buns",
      "2 potatoes, boiled and mashed",
      "1 onion, chopped",
      "1 green chili, chopped",
      "1/2 teaspoon mustard seeds",
      "1/4 teaspoon turmeric powder",
      "Salt to taste",
      "1 cup gram flour (for batter)",
      "Water for batter",
      "Oil for frying",
      "Green chutney and tamarind chutney",
    ],
    steps: [
      "In a pan, heat oil, add mustard seeds, onions, and green chili, and sauté until golden.",
      "Add mashed potatoes, turmeric powder, and salt. Mix well and let it cool.",
      "Form small balls from the potato mixture.",
      "In a separate bowl, mix gram flour and water to make a thick batter.",
      "Dip the potato balls in the batter and deep fry until golden.",
      "Slice the pav buns, add chutneys and place the fried vada inside.",
      "Serve hot.",
    ],
    instructions:
      "A popular street food from Mumbai, consisting of a spiced potato fritter served in a bun with chutneys.",
    image: "vada pav.jpg",
  },
  {
    name: "Dhokla",
    ingredients: [
      "1 cup gram flour (besan)",
      "1/2 cup yogurt",
      "1/2 teaspoon turmeric powder",
      "1 teaspoon baking soda",
      "1 teaspoon mustard seeds",
      "1 tablespoon oil",
      "Salt to taste",
      "Fresh coriander leaves for garnish",
    ],
    steps: [
      "In a bowl, mix gram flour, yogurt, turmeric powder, and salt with water to form a thick batter.",
      "Add baking soda and mix well just before steaming.",
      "Pour the batter into a greased steamer plate and steam for 15-20 minutes.",
      "In a pan, heat oil, add mustard seeds, and pour over the steamed dhokla.",
      "Garnish with coriander leaves and serve.",
    ],
    instructions:
      "A fluffy, savory cake made from gram flour, originating from Gujarat, usually served as a snack or breakfast.",
    image: "dhokla.jpg",
  },
  {
    name: "Macaroni",
    ingredients: [
      "1 cup macaroni pasta",
      "1 onion, chopped",
      "1 tomato, chopped",
      "1/2 capsicum, chopped",
      "1/2 teaspoon turmeric powder",
      "1/2 teaspoon red chili powder",
      "1/2 teaspoon garam masala",
      "Salt to taste",
      "Fresh coriander leaves for garnish",
      "Oil for cooking",
    ],
    steps: [
      "Cook the macaroni pasta according to package instructions, drain, and set aside.",
      "In a pan, heat oil and sauté onions until translucent.",
      "Add tomatoes, capsicum, turmeric powder, red chili powder, and salt. Cook until tomatoes are soft.",
      "Add the cooked macaroni and mix well with the spices.",
      "Garnish with fresh coriander leaves and serve hot.",
    ],
    instructions:
      "A flavorful Indian twist on classic macaroni, cooked with spices and vegetables.",
    image: "macaroni.jpg",
  },
  {
    name: "Veg Vermicelli",
    ingredients: [
      "1 cup vermicelli (semiya)",
      "1/2 onion, chopped",
      "1/2 cup mixed vegetables (carrot, peas, beans)",
      "1/2 teaspoon mustard seeds",
      "1/2 teaspoon cumin seeds",
      "1 green chili, chopped",
      "Salt to taste",
      "Fresh coriander leaves for garnish",
      "Oil for cooking",
      "2 cups water",
    ],
    steps: [
      "Dry roast the vermicelli until golden brown and set aside.",
      "In a pan, heat oil and add mustard seeds, cumin seeds, and green chili.",
      "Add onions and sauté until translucent. Then add mixed vegetables and cook until tender.",
      "Add water and salt, and bring it to a boil.",
      "Add the roasted vermicelli and cook until the water is absorbed and the vermicelli is soft.",
      "Garnish with coriander leaves and serve hot.",
    ],
    instructions:
      "A savory breakfast dish made with vermicelli and vegetables, lightly spiced and satisfying.",
    image: "veg vermicelli.jpg",
  },
  {
    name: "Buns Sambar",
    ingredients: [
      "1 cup all-purpose flour",
      "1 ripe banana, mashed",
      "2 tablespoons sugar",
      "1/4 teaspoon salt",
      "1/4 teaspoon baking soda",
      "2 tablespoons yogurt",
      "1/2 teaspoon cumin seeds (optional)",
      "Oil for deep frying",
    ],
    steps: [
      "In a bowl, combine mashed banana, sugar, salt, and yogurt. Mix until smooth.",
      "Add flour, baking soda, and cumin seeds (optional). Mix to form a soft dough.",
      "Cover and let the dough rest for 2-3 hours for best results.",
      "After resting, divide the dough into small balls and roll each ball into circles about 3–4 inches in diameter.",
      "Heat oil in a pan for deep frying. Fry each bun until golden brown and puffed on both sides.",
      "Drain on paper towels to remove excess oil.",
    ],
    sambar: [],
    ingredients: [
      "1/2 cup toor dal (pigeon pea lentils)",
      "1 small onion, chopped",
      "1 small tomato, chopped",
      "1/2 cup mixed vegetables (carrot, drumstick, potato, etc.), chopped",
      "2-3 cups water",
      "1 tablespoon tamarind paste",
      "1/2 teaspoon turmeric powder",
      "Salt to taste",
      "1 tablespoon oil",
      "1 teaspoon mustard seeds",
      "1/2 teaspoon cumin seeds",
      "1/4 teaspoon fenugreek seeds",
      "2 dried red chilies",
      "1 sprig curry leaves",
      "1 tablespoon sambar powder",
      "Fresh coriander leaves for garnish",
    ],
    steps: [
      "Rinse and cook toor dal with turmeric and water until soft. Mash and set aside.",
      "In a pot, heat oil and add mustard seeds, cumin seeds, fenugreek seeds, red chilies, and curry leaves. Let them splutter.",
      "Add onions and sauté until soft, then add tomatoes and cook until they break down.",
      "Add mixed vegetables, sambar powder, salt, and tamarind paste. Cook until vegetables are tender.",
      "Add the mashed dal to the pot and simmer, adding water to adjust consistency if needed.",
      "Garnish with fresh coriander leaves and serve hot.",
    ],
    instructions:
      "Serve hot buns with sambar. Enjoy the sweet and fluffy buns dipped in flavorful sambar for a delicious breakfast or snack.",
    image: "buns.jpg",
  },
  {
    name: "Plain Dosa",
    ingredients: [
      "1 cup rice",
      "1/4 cup urad dal (split black gram)",
      "1/2 teaspoon fenugreek seeds",
      "Salt to taste",
      "Water as needed",
      "Ghee or oil for cooking",
    ],
    steps: [
      "Soak rice, urad dal, and fenugreek seeds for 6 hours.",
      "Grind the soaked ingredients into a smooth batter, adding water as needed.",
      "Let the batter ferment overnight.",
      "Heat a non-stick griddle or tawa, and pour a ladle of batter to spread it thin.",
      "Cook until crispy and golden brown on both sides.",
      "Serve with coconut chutney and sambar.",
    ],
    instructions:
      "A thin and crispy South Indian crepe made from fermented rice and lentil batter.",
    image: "plain dosa.jpg",
  },
  {
    name: "Sheera",
    ingredients: [
      "1 cup semolina (sooji)",
      "1/4 cup ghee",
      "1/4 cup sugar",
      "2 cups water",
      "1/2 teaspoon cardamom powder",
      "Cashews, raisins, and almonds for garnish",
    ],
    steps: [
      "Heat ghee in a pan and roast the semolina until golden brown.",
      "In a separate pot, bring water to a boil and add sugar.",
      "Pour the boiling water and sugar mixture into the roasted semolina, stirring continuously.",
      "Cook until the semolina absorbs the water and becomes soft.",
      "Add cardamom powder and mix well.",
      "Garnish with cashews, raisins, and almonds.",
      "Serve hot as a sweet breakfast or dessert.",
    ],
    instructions:
      "A sweet and fragrant semolina dessert, often enjoyed as a breakfast or snack in India.",
    image: "sheera.jpg",
  },
  {
    name: "Pineapple Sheera",
    ingredients: [
      "1 cup semolina (sooji)",
      "1/4 cup ghee",
      "1/4 cup sugar",
      "1 cup pineapple, chopped",
      "2 cups water",
      "1/2 teaspoon cardamom powder",
      "Cashews, raisins, and almonds for garnish",
    ],
    steps: [
      "Heat ghee in a pan and roast the semolina until golden brown.",
      "In a separate pot, bring water to a boil and add sugar and chopped pineapple.",
      "Once the water boils, add it to the roasted semolina, stirring continuously.",
      "Cook until the semolina absorbs the water and becomes soft.",
      "Add cardamom powder and mix well.",
      "Garnish with cashews, raisins, and almonds.",
      "Serve hot as a delicious breakfast or dessert.",
    ],
    instructions:
      "A variation of the classic sheera, with the addition of sweet and tangy pineapple.",
    image: "pineapple sheera.jpg",
  },
  {
    name: "Idli Sambar",
    ingredients: [
      "1 cup rice",
      "1/4 cup urad dal (split black gram)",
      "1/2 teaspoon fenugreek seeds",
      "Salt to taste",
      "Water as needed",
      "For Sambar:",
      "1 cup toor dal (pigeon peas)",
      "1 onion, chopped",
      "1 tomato, chopped",
      "1/2 teaspoon mustard seeds",
      "1/2 teaspoon cumin seeds",
      "1/2 teaspoon turmeric powder",
      "1/2 teaspoon sambar powder",
      "Salt to taste",
      "Tamarind pulp (optional)",
      "Fresh coriander leaves for garnish",
    ],
    steps: [
      "Soak rice, urad dal, and fenugreek seeds for 6 hours.",
      "Grind the soaked ingredients into a smooth batter, adding water as needed.",
      "Let the batter ferment overnight.",
      "Grease the idli molds and pour the batter into them.",
      "Steam the idlis for 10-15 minutes until they are cooked.",
      "For the sambar, cook toor dal in a pressure cooker until soft.",
      "In a pan, heat oil, add mustard seeds, cumin seeds, and onions, and sauté.",
      "Add tomatoes, turmeric powder, sambar powder, and cooked dal. Add tamarind pulp if using.",
      "Simmer for 10 minutes and garnish with fresh coriander leaves.",
      "Serve hot idlis with sambar.",
    ],
    instructions:
      "A classic South Indian dish made with steamed rice cakes (idlis) served with a spicy lentil soup (sambar).",
    image: "idli.jpg",
  },
  {
    name: "Chapati",
    ingredients: [
      "2 cups whole wheat flour",
      "1/2 teaspoon salt",
      "Water as needed",
      "1 tablespoon oil or ghee (optional)",
    ],
    steps: [
      "Mix the wheat flour and salt in a bowl.",
      "Add water little by little and knead the dough until soft and smooth.",
      "Cover the dough and let it rest for 15-20 minutes.",
      "Divide the dough into small balls and roll them into flat discs.",
      "Heat a tawa or griddle, and cook the chapati until golden brown on both sides.",
      "Optionally, brush with oil or ghee and serve hot.",
    ],
    instructions:
      "A simple and staple Indian flatbread made with whole wheat flour, often served with curries and vegetables.",
    image: "chapathi.jpg",
  },
  {
    name: "Tea",
    ingredients: [
      "2 cups water",
      "1 tablespoon tea leaves",
      "2 teaspoons sugar (or to taste)",
      "1/2 cup milk",
    ],
    steps: [
      "Boil water in a saucepan.",
      "Add the tea leaves and let it steep for 2-3 minutes.",
      "Add sugar to taste, then pour in the milk.",
      "Simmer for another 2-3 minutes and strain into cups.",
      "Serve hot.",
    ],
    instructions:
      "A simple Indian-style tea made with tea leaves, milk, and sugar, often enjoyed throughout the day.",
    image: "tea.jpg",
  },
  {
    name: "Masala Tea",
    ingredients: [
      "2 cups water",
      "1 tablespoon tea leaves",
      "1-2 teaspoons sugar (or to taste)",
      "1/2 cup milk",
      "2-3 cardamom pods, crushed",
      "1 small piece of ginger, grated",
      "1/2 teaspoon cinnamon powder",
      "1/4 teaspoon black pepper (optional)",
    ],
    steps: [
      "Boil water in a saucepan.",
      "Add tea leaves, crushed cardamom, ginger, cinnamon, and black pepper.",
      "Let the spices steep for 2-3 minutes.",
      "Add sugar and milk, then simmer for 2-3 more minutes.",
      "Strain the tea into cups and serve hot.",
    ],
    instructions:
      "A spiced version of tea, made with a variety of aromatic spices such as cardamom, ginger, and cinnamon.",
    image: "masala tea.jpg",
  },
  {
    name: "Coffee",
    ingredients: [
      "2 cups water",
      "1 tablespoon coffee powder",
      "2 teaspoons sugar (or to taste)",
      "1/2 cup milk",
    ],
    steps: [
      "Boil water in a saucepan.",
      "Add coffee powder and let it steep for 2-3 minutes.",
      "Add sugar and milk, then simmer for another 2-3 minutes.",
      "Strain the coffee into cups and serve hot.",
    ],
    instructions:
      "A classic coffee made with coffee powder, sugar, and milk, perfect for a morning boost.",
    image: "hot coffee.jpg",
  },
  {
    name: "Badam Milk",
    ingredients: [
      "1 cup milk",
      "10-12 almonds (badam), soaked overnight",
      "2 teaspoons sugar (or to taste)",
      "1/4 teaspoon cardamom powder",
      "A few strands of saffron (optional)",
    ],
    steps: [
      "Blanch and peel the soaked almonds, then grind them into a fine paste.",
      "Heat milk in a pan, add the almond paste, sugar, and cardamom powder.",
      "Simmer the milk for 5-10 minutes, stirring occasionally.",
      "Add saffron strands (if using) and mix well.",
      "Serve hot or chilled.",
    ],
    instructions:
      "A rich and nutritious milk drink made with almond paste, cardamom, and saffron, often served as a health tonic.",
    image: "Badam milk.jpg",
  },
  {
    name: "Kesar Milk",
    ingredients: [
      "1 cup milk",
      "1/4 teaspoon saffron strands",
      "2 teaspoons sugar (or to taste)",
      "A pinch of cardamom powder",
    ],
    steps: [
      "Soak the saffron strands in warm milk for 10-15 minutes.",
      "Heat the milk in a pan, add the saffron milk, sugar, and cardamom powder.",
      "Simmer for 5 minutes, stirring occasionally.",
      "Serve hot or chilled, garnished with more saffron strands.",
    ],
    instructions:
      "A fragrant milk drink infused with saffron and cardamom, perfect as a soothing and aromatic beverage.",
    image: "Kesar milk.jpg",
  },
  {
    name: "Maggie",
    ingredients: [
      "1 packet Maggie noodles",
      "2 cups water",
      "1 tablespoon oil or butter",
      "1/2 teaspoon garam masala",
      "1/4 teaspoon chili powder (optional)",
      "Salt to taste",
      "Chopped vegetables (optional)",
    ],
    steps: [
      "Boil 2 cups of water in a pan.",
      "Add the Maggie noodles and cook for 2-3 minutes until they soften.",
      "Add the tastemaker (spice mix) from the Maggie packet.",
      "Stir in oil or butter, and add garam masala, chili powder, and salt.",
      "Mix well and cook for another 2-3 minutes until the noodles are fully cooked.",
      "Optionally, you can add chopped vegetables like peas, carrots, or bell peppers for extra flavor.",
    ],
    instructions:
      "A quick and easy noodle dish, made with Maggie noodles and a simple spice mix.",
    image: "maggie.jpg",
  },
  {
    name: "Veg Noodles",
    ingredients: [
      "200g noodles (your choice of variety)",
      "1 tablespoon soy sauce",
      "1 tablespoon chili sauce",
      "1/2 teaspoon vinegar",
      "1 tablespoon oil",
      "1 onion, chopped",
      "1 carrot, chopped",
      "1/2 cup peas",
      "1/2 cup cabbage, shredded",
      "Salt and pepper to taste",
    ],
    steps: [
      "Cook the noodles according to the package instructions and drain.",
      "Heat oil in a pan and sauté the onion for a minute.",
      "Add the carrots, peas, and cabbage and cook for 3-4 minutes until soft.",
      "Add soy sauce, chili sauce, and vinegar. Stir well.",
      "Add the cooked noodles, and mix well.",
      "Season with salt and pepper and stir-fry for 2-3 minutes.",
    ],
    instructions:
      "A quick and easy stir-fried noodle dish with vegetables and sauces.",
    image: "Veg noodles.jpg",
  },
  {
    name: "Chicken Noodles",
    ingredients: [
      "200g noodles",
      "1 chicken breast, sliced into thin strips",
      "2 tablespoons soy sauce",
      "1 tablespoon oyster sauce",
      "1 teaspoon ginger-garlic paste",
      "1 onion, sliced",
      "1 bell pepper, sliced",
      "2-3 cloves garlic, minced",
      "1 tablespoon oil",
      "Salt and pepper to taste",
    ],
    steps: [
      "Cook the noodles according to package instructions and set aside.",
      "Heat oil in a pan, and sauté garlic until fragrant.",
      "Add the chicken strips and cook until browned.",
      "Add onion, bell pepper, and sauté until vegetables are tender.",
      "Add soy sauce, oyster sauce, and cooked noodles. Toss well.",
      "Season with salt and pepper to taste and stir-fry for another 2-3 minutes.",
    ],
    instructions:
      "A delicious stir-fried noodle dish with chicken, vegetables, and savory sauces.",
    image: "chicken noodles.jpg",
  },
  {
    name: "Egg Noodles",
    ingredients: [
      "200g noodles",
      "2 eggs, beaten",
      "1 tablespoon soy sauce",
      "1 tablespoon chili sauce",
      "1/2 teaspoon vinegar",
      "1 onion, chopped",
      "1/2 bell pepper, chopped",
      "1 tablespoon oil",
      "Salt and pepper to taste",
    ],
    steps: [
      "Cook the noodles according to package instructions and set aside.",
      "Heat oil in a pan and scramble the beaten eggs until cooked. Remove from the pan and set aside.",
      "In the same pan, sauté the onion and bell pepper for 2-3 minutes.",
      "Add the cooked noodles, soy sauce, chili sauce, and vinegar. Stir well.",
      "Add the scrambled eggs and toss everything together.",
      "Season with salt and pepper to taste and cook for another 2 minutes.",
    ],
    instructions:
      "Stir-fried noodles with scrambled eggs, veggies, and a tangy sauce.",
    image: "Egg noodles.jpg",
  },
  {
    name: " Veg Fried Rice",
    ingredients: [
      "2 cups cooked rice (preferably cold)",
      "1/2 cup mixed vegetables (peas, carrots, beans)",
      "1/2 onion, chopped",
      "1 tablespoon soy sauce",
      "1/2 teaspoon chili sauce",
      "1/2 teaspoon vinegar",
      "1 tablespoon oil",
      "2-3 cloves garlic, minced",
      "Salt and pepper to taste",
    ],
    steps: [
      "Heat oil in a pan and sauté garlic until fragrant.",
      "Add the chopped onion and vegetables. Stir-fry for 3-4 minutes.",
      "Add the cold rice and toss well.",
      "Add soy sauce, chili sauce, and vinegar. Stir-fry for 5 minutes.",
      "Season with salt and pepper and serve hot.",
    ],
    instructions:
      "A quick stir-fried rice dish with mixed vegetables and savory sauces.",
    image: "veg fried rice.jpg",
  },
  {
    name: "Chicken Fried Rice",
    ingredients: [
      "2 cups cooked rice (preferably cold)",
      "1 chicken breast, diced",
      "1/2 cup mixed vegetables (peas, carrots, beans)",
      "1 onion, chopped",
      "1 tablespoon soy sauce",
      "1/2 teaspoon chili sauce",
      "1/2 teaspoon vinegar",
      "1 tablespoon oil",
      "2-3 cloves garlic, minced",
      "Salt and pepper to taste",
    ],
    steps: [
      "Heat oil in a pan and sauté garlic until fragrant.",
      "Add the diced chicken and cook until browned.",
      "Add onion and mixed vegetables. Cook for another 3-4 minutes.",
      "Add the cold rice, soy sauce, chili sauce, and vinegar. Stir-fry for 5 minutes.",
      "Season with salt and pepper and serve hot.",
    ],
    instructions:
      "A delicious fried rice dish with chicken, vegetables, and savory sauces.",
    image: "chicken fried rice .jpg",
  },
  {
    name: "Egg Fried Rice",
    ingredients: [
      "2 cups cooked rice (preferably cold)",
      "2 eggs, beaten",
      "1/2 cup mixed vegetables (peas, carrots, beans)",
      "1/2 onion, chopped",
      "1 tablespoon soy sauce",
      "1/2 teaspoon chili sauce",
      "1/2 teaspoon vinegar",
      "1 tablespoon oil",
      "2-3 cloves garlic, minced",
      "Salt and pepper to taste",
    ],
    steps: [
      "Heat oil in a pan and scramble the eggs until cooked. Remove and set aside.",
      "In the same pan, sauté garlic until fragrant.",
      "Add the chopped onion and mixed vegetables. Stir-fry for 3-4 minutes.",
      "Add the cold rice, soy sauce, chili sauce, and vinegar. Stir-fry for 5 minutes.",
      "Add the scrambled eggs and mix well.",
      "Season with salt and pepper and serve hot.",
    ],
    instructions:
      "A tasty fried rice dish with scrambled eggs, vegetables, and flavorful sauces.",
    image: "egg fried rice.jpg",
  },
  {
    name: "Jeera Rice",
    ingredients: [
      "1 cup basmati rice",
      "1 tablespoon cumin seeds (jeera)",
      "1 tablespoon oil or ghee",
      "2 cups water",
      "Salt to taste",
    ],
    steps: [
      "Wash the rice thoroughly and soak it in water for 15 minutes.",
      "Heat oil or ghee in a pan, add cumin seeds, and sauté until they splutter.",
      "Add the soaked rice, water, and salt. Bring it to a boil.",
      "Reduce the heat to low, cover, and cook for 10-12 minutes until the rice is fully cooked.",
      "Fluff the rice with a fork and serve hot.",
    ],
    instructions:
      "A simple and aromatic rice dish flavored with cumin seeds, often served with curries.",
    image: "jeera rice.jpg",
  },
  {
    name: "Plain Rice",
    ingredients: ["1 cup basmati rice", "2 cups water", "Salt to taste"],
    steps: [
      "Wash the rice thoroughly and soak it in water for 15 minutes.",
      "In a pan, add the soaked rice, water, and salt.",
      "Bring to a boil, then reduce the heat and cover the pan.",
      "Simmer for 10-12 minutes until the rice is fully cooked.",
      "Fluff the rice with a fork and serve hot.",
    ],
    instructions:
      "A basic rice dish, cooked with water and salt, served as a side for curries and dishes.",
    image: "plain rice.jpg",
  },
  {
    name: "Pani Puri",
    ingredients: [
      "Pani puri shells (store-bought or homemade)",
      "1/2 cup boiled potatoes, mashed",
      "1/2 cup boiled chickpeas",
      "1/4 cup finely chopped onions",
      "1/4 cup tamarind chutney",
      "1/4 cup green chutney (mint-coriander)",
      "Chaat masala to taste",
      "Black salt to taste",
      "Cumin powder to taste",
      "Salt to taste",
      "Fresh coriander leaves for garnish",
    ],
    steps: [
      "Mix mashed potatoes, boiled chickpeas, onions, chaat masala, black salt, and salt in a bowl.",
      "Stuff each puri with the potato-chickpea mixture.",
      "Fill the puris with green chutney, tamarind chutney, and a pinch of cumin powder.",
      "Pour chilled pani (flavored water) into each puri just before serving.",
      "Garnish with fresh coriander and serve immediately.",
    ],
    instructions:
      "A popular street food made with crispy puris filled with spicy and tangy water, potatoes, chickpeas, and chutneys.",
    image: "pani puri.jpg",
  },
  {
    name: "Bhel Puri",
    ingredients: [
      "2 cups puffed rice",
      "1/4 cup sev (crunchy noodles)",
      "1/4 cup roasted peanuts",
      "1/4 cup finely chopped onions",
      "1/4 cup boiled potatoes, diced",
      "2 tablespoons tamarind chutney",
      "2 tablespoons green chutney",
      "1 teaspoon chaat masala",
      "Black salt to taste",
      "Fresh coriander for garnish",
    ],
    steps: [
      "In a large mixing bowl, combine puffed rice, sev, roasted peanuts, onions, and boiled potatoes.",
      "Add tamarind chutney, green chutney, chaat masala, and black salt.",
      "Toss everything together until well mixed.",
      "Garnish with fresh coriander leaves and serve immediately.",
    ],
    instructions:
      "A savory and crunchy snack made with puffed rice, chutneys, sev, and spices.",
    image: "bhel puri.jpg",
  },
  {
    name: "Dahi Puri",
    ingredients: [
      "Puri shells (store-bought or homemade)",
      "1/2 cup boiled potatoes, mashed",
      "1/4 cup boiled chickpeas",
      "1/2 cup yogurt, whipped",
      "1 tablespoon tamarind chutney",
      "1 tablespoon green chutney",
      "Chaat masala to taste",
      "Black salt to taste",
      "Red chili powder to taste",
      "Fresh coriander leaves for garnish",
    ],
    steps: [
      "Stuff each puri with mashed potatoes and chickpeas.",
      "Top each puri with whipped yogurt, tamarind chutney, green chutney, chaat masala, and black salt.",
      "Sprinkle red chili powder on top and garnish with fresh coriander leaves.",
      "Serve immediately and enjoy the tangy, spicy flavor.",
    ],
    instructions:
      "A delightful chaat made by filling puris with mashed potatoes, chickpeas, and yogurt, then topped with chutneys and spices.",
    image: "dahi puri.jpg",
  },
  {
    name: "Sev Puri",
    ingredients: [
      "Puri shells",
      "1/2 cup boiled potatoes, mashed",
      "1/4 cup chopped onions",
      "1/4 cup roasted peanuts",
      "1/4 cup sev (crunchy noodles)",
      "1 tablespoon tamarind chutney",
      "1 tablespoon green chutney",
      "Chaat masala to taste",
      "Black salt to taste",
      "Fresh coriander leaves for garnish",
    ],
    steps: [
      "Stuff each puri with mashed potatoes, onions, and roasted peanuts.",
      "Top with tamarind chutney, green chutney, and a sprinkle of chaat masala.",
      "Add a generous amount of sev on top and garnish with fresh coriander leaves.",
      "Serve immediately and enjoy.",
    ],
    instructions:
      "A tasty and crunchy chaat with puris stuffed with potatoes, chutneys, and sev.",
    image: "sev puri.jpg",
  },
  {
    name: "Samosa Chaat",
    ingredients: [
      "2 samosas (store-bought or homemade)",
      "1/2 cup yogurt, whipped",
      "1 tablespoon tamarind chutney",
      "1 tablespoon green chutney",
      "Chaat masala to taste",
      "Black salt to taste",
      "Fresh coriander leaves for garnish",
    ],
    steps: [
      "Crush the samosas and place them on a serving plate.",
      "Top with whipped yogurt, tamarind chutney, and green chutney.",
      "Sprinkle chaat masala and black salt over the samosas.",
      "Garnish with fresh coriander leaves and serve immediately.",
    ],
    instructions:
      "A delicious chaat made by crushing samosas and topping them with yogurt, chutneys, and spices.",
    image: "samosa chaat.jpg",
  },
  {
    name: "Fruit Chaat",
    ingredients: [
      "1/2 cup pomegranate seeds",
      "1/2 cup chopped apple",
      "1/2 cup chopped cucumber",
      "1/4 cup chopped papaya",
      "1 tablespoon lemon juice",
      "1 tablespoon chaat masala",
      "1/2 teaspoon black salt",
      "1/2 teaspoon cumin powder",
      "Fresh coriander leaves for garnish",
    ],
    steps: [
      "Mix all the fruits in a large bowl.",
      "Add lemon juice, chaat masala, black salt, and cumin powder.",
      "Toss everything together gently.",
      "Garnish with fresh coriander leaves and serve.",
    ],
    instructions:
      "A refreshing and tangy chaat made with fresh fruits, spices, and a zesty dressing.",
    image: "fruit chaat.jpg",
  },
  {
    name: "Chana Chaat",
    ingredients: [
      "1/2 cup boiled chickpeas",
      "1/4 cup chopped onions",
      "1 tablespoon tamarind chutney",
      "1 tablespoon green chutney",
      "1/2 teaspoon cumin powder",
      "1/2 teaspoon red chili powder",
      "Black salt to taste",
      "Fresh coriander leaves for garnish",
    ],
    steps: [
      "In a mixing bowl, combine boiled chickpeas with onions.",
      "Add tamarind chutney, green chutney, cumin powder, red chili powder, and black salt.",
      "Toss everything together until well combined.",
      "Garnish with fresh coriander leaves and serve.",
    ],
    instructions:
      "A savory and spicy chaat made with chickpeas, onions, chutneys, and spices.",
    image: "chana chaat .jpg",
  },
  {
    name: "cucumber Salad",
    ingredients: [
      "1 cucumber, diced",
      "1 tomato, diced",
      "1 onion, finely chopped",
      "1/4 cup coriander leaves, chopped",
      "1 green chili, finely chopped",
      "1 tablespoon lemon juice",
      "Salt to taste",
      "Black pepper to taste",
      "Chaat masala (optional)",
    ],
    steps: [
      "Combine cucumber, tomato, onion, and green chili in a bowl.",
      "Add lemon juice, salt, and pepper, and mix well.",
      "Garnish with coriander leaves and sprinkle with chaat masala (optional).",
    ],
    instructions:
      "A simple Indian salad with diced cucumber, tomatoes, onions, and a tangy lemon dressing.",
    image: "cucumber salad.jpg",
  },
  {
    name: "Carrot and Cucumber Salad",
    ingredients: [
      "1 cucumber, grated",
      "1 carrot, grated",
      "1 tablespoon lemon juice",
      "1 tablespoon olive oil",
      "1/4 teaspoon roasted cumin powder",
      "1/4 teaspoon black salt",
      "Coriander leaves for garnish",
    ],
    steps: [
      "Grate the cucumber and carrot into a bowl.",
      "Add lemon juice, olive oil, roasted cumin powder, and black salt.",
      "Toss gently and garnish with coriander leaves.",
    ],
    instructions:
      "A refreshing and crunchy salad with grated carrots and cucumber, flavored with roasted cumin powder.",
    image: "carrot and cucumber salad.jpg",
  },
  {
    name: "Beetroot Salad",
    ingredients: [
      "1 beetroot, boiled and grated",
      "1/4 cup onion, finely chopped",
      "1/4 cup cucumber, diced",
      "1 tablespoon lemon juice",
      "1/2 teaspoon black salt",
      "1/4 teaspoon black pepper",
      "1 tablespoon fresh coriander leaves, chopped",
    ],
    steps: [
      "In a bowl, combine grated beetroot, onion, and cucumber.",
      "Add lemon juice, black salt, and black pepper, and toss well.",
      "Garnish with fresh coriander leaves.",
    ],
    instructions:
      "A healthy salad made with boiled grated beetroot, cucumber, and a tangy dressing.",
    image: "beetroot and cucumber salad.jpg",
  },
  {
    name: "Pineapple Salad",
    ingredients: [
      "1 cup pineapple, diced",
      "1/4 teaspoon black salt",
      "1/2 teaspoon chaat masala",
      "1 tablespoon lemon juice",
      "Coriander leaves for garnish",
    ],
    steps: [
      "Combine diced pineapple with black salt, chaat masala, and lemon juice.",
      "Toss gently to coat the pineapple with the spices.",
      "Garnish with fresh coriander leaves.",
    ],
    instructions:
      "A tangy and sweet salad made with fresh pineapple and spiced with black salt and chaat masala.",
    image: "pineapple salad.jpg",
  },
  {
    name: "Cabbage and Carrot Salad",
    ingredients: [
      "1 cup cabbage, shredded",
      "1/2 cup carrot, grated",
      "1 tablespoon lemon juice",
      "1/4 teaspoon sugar",
      "Salt to taste",
      "1/4 teaspoon black pepper",
      "Coriander leaves for garnish",
    ],
    steps: [
      "In a bowl, combine shredded cabbage and grated carrot.",
      "Add lemon juice, sugar, salt, and black pepper, and mix well.",
      "Garnish with fresh coriander leaves.",
    ],
    instructions:
      "A simple salad made with shredded cabbage and grated carrot, seasoned with a tangy and sweet dressing.",
    image: "cabbage and carrot salad.jpg",
  },
  {
    name: "Mango Salad",
    ingredients: [
      "1 mango, peeled and diced",
      "1/4 cup onion, finely chopped",
      "1 tablespoon lemon juice",
      "1/4 teaspoon black salt",
      "1/2 teaspoon chaat masala",
      "Fresh coriander leaves for garnish",
    ],
    steps: [
      "Combine diced mango and chopped onion in a bowl.",
      "Add lemon juice, black salt, and chaat masala.",
      "Toss gently and garnish with fresh coriander leaves.",
    ],
    instructions:
      "A sweet and tangy salad with fresh mango, onion, and a sprinkle of chaat masala.",
    image: "mango salad.jpg",
  },
  {
    name: "Fruit Salad",
    ingredients: [
      "1 apple, diced",
      "1 banana, sliced",
      "1 orange, segmented",
      "1/2 cup pomegranate seeds",
      "1/2 cup grapes (red or green), halved",
      "1/2 cup pineapple, diced",
      "1/2 cup papaya or mango, diced",
      "1/4 teaspoon chaat masala (optional)",
      "1 tablespoon honey (optional)",
      "1 tablespoon lemon juice",
      "Fresh mint leaves for garnish",
    ],
    steps: [
      "In a large bowl, combine all the diced fruits: apple, banana, orange segments, pomegranate seeds, grapes, pineapple, and papaya or mango.",
      "Drizzle the fruit salad with lemon juice to prevent the fruits from browning and to add a tangy flavor.",
      "If desired, add a pinch of chaat masala for a spiced twist and a tablespoon of honey for added sweetness.",
      "Gently toss the fruit to combine all the ingredients.",
      "Garnish with fresh mint leaves for added fragrance and color.",
      "Serve chilled and enjoy your healthy, colorful fruit salad.",
    ],
    instructions:
      "A vibrant and refreshing fruit salad made with a variety of seasonal fruits, seasoned with lemon juice, honey, and a touch of chaat masala.",
    image: "fruit salad.jpg",
  },
  {
    name: "Fruit Custard",
    ingredients: [
      "2 cups milk",
      "2 tablespoons custard powder (vanilla flavor)",
      "3 tablespoons sugar",
      "1/2 teaspoon vanilla essence",
      "1/2 cup diced apples",
      "1/2 cup diced bananas",
      "1/2 cup pomegranate seeds",
      "1/2 cup grapes (red or green), halved",
      "1/2 cup pineapple, diced",
      "1/2 cup orange segments",
      "Fresh mint leaves for garnish",
    ],
    steps: [
      "In a small bowl, mix the custard powder with a few tablespoons of milk to make a smooth paste.",
      "Heat the remaining milk in a pan over medium heat. Add sugar and stir until dissolved.",
      "Once the milk starts boiling, add the custard paste and cook on low heat, stirring constantly, until the custard thickens.",
      "Remove from heat and let the custard cool to room temperature.",
      "Once cooled, refrigerate the custard for 30 minutes.",
      "To assemble, combine the diced fruits in a bowl.",
      "Pour the chilled custard over the fruits and gently mix to coat the fruits.",
      "Garnish with fresh mint leaves and serve chilled.",
    ],
    instructions: [
      "A creamy fruit custard made with a variety of fresh fruits mixed into a smooth vanilla custard.",
    ],
    image: "fruit custard.jpg",
  },
  {
    name: "Caramel Custard",
    ingredients: [
      "1 cup sugar (for caramel)",
      "2 cups milk",
      "3 large eggs",
      "1/2 cup sugar",
      "1 teaspoon vanilla extract",
      "A pinch of salt",
    ],
    steps: [
      "In a saucepan, heat 1 cup of sugar on low heat until it melts and turns golden brown, stirring occasionally. Once melted and caramelized, pour it immediately into a round baking dish or individual ramekins to coat the bottom evenly. Set aside to let the caramel harden.",
      "In a separate saucepan, heat 2 cups of milk over medium heat until warm but not boiling. Remove from heat and let it cool slightly.",
      "In a mixing bowl, whisk together 3 large eggs, 1/2 cup sugar, 1 teaspoon vanilla extract, and a pinch of salt until smooth and well combined.",
      "Gradually pour the warm milk into the egg mixture, whisking constantly to avoid curdling.",
      "Strain the custard mixture through a fine sieve to ensure a smooth texture, then pour it over the caramel-coated baking dish or ramekins.",
      "Place the baking dish or ramekins in a larger baking pan. Pour hot water into the larger pan until it reaches halfway up the sides of the baking dish or ramekins, creating a water bath.",
      "Bake at 325°F (160°C) for about 45-60 minutes, or until the custard is set but still slightly jiggly in the center.",
      "Remove from the oven and let it cool in the water bath, then refrigerate for at least 2 hours or until fully chilled.",
      "To serve, run a knife around the edges of the custard, then invert onto a plate to release the caramel topping.",
    ],
    instructions:
      "A classic caramel custard dessert with a creamy custard base and a rich caramel topping.",
    image: "caramel custard.jpg",
  },
];
