// recipe3.js
export const recipe3 = [
  {
    name: "Vegetable Pasta",
    ingredients: [
      "200 grams pasta (penne or fusilli)",
      "2 tablespoons olive oil",
      "3 garlic cloves, minced",
      "1/2 onion, chopped",
      "1/2 bell pepper, chopped",
      "1 small carrot, thinly sliced",
      "1/2 cup broccoli florets",
      "1/2 zucchini, chopped",
      "1 cup tomato puree (or crushed tomatoes)",
      "Salt to taste",
      "1/2 teaspoon black pepper",
      "1/2 teaspoon Italian seasoning (optional)",
      "Fresh basil or parsley, chopped (for garnish)",
      "Parmesan cheese, grated (optional, for garnish)",
    ],
    steps: [
      "Bring a large pot of salted water to a boil and cook the pasta according to package instructions until al dente. Drain and set aside.",
      "In a large skillet, heat olive oil over medium heat. Add minced garlic and chopped onion, and sauté until softened.",
      "Add bell pepper, carrot, broccoli, and zucchini to the skillet. Sauté for 5-7 minutes until the vegetables are tender but still slightly crisp.",
      "Pour in the tomato puree, salt, black pepper, and Italian seasoning (if using). Simmer for 5-10 minutes, stirring occasionally.",
      "Add the cooked pasta to the skillet, tossing to coat the pasta evenly in the sauce and vegetables.",
      "Serve hot, garnished with fresh basil or parsley and grated Parmesan cheese, if desired.",
    ],
    instructions: "Pair with garlic bread or a side salad for a complete meal.",
    image: "pasta.jpg",
  },
  {
    name: "Apple Juice",
    ingredients: [
      "4-5 fresh apples",
      "1 tablespoon lemon juice (optional)",
      "Ice cubes (optional)",
    ],
    steps: [
      "Wash and core the apples.",
      "Cut them into chunks and blend them until smooth.",
      "Strain the juice if you prefer a smooth consistency.",
      "Add lemon juice for a tangy flavor, and serve chilled.",
    ],
    instructions:
      "A sweet and tangy juice made from fresh apples, perfect for a healthy beverage.",
    image: "apple juice.jpg",
  },
  {
    name: "Mango Juice",
    ingredients: [
      "2 ripe mangoes",
      "1 cup water or coconut water",
      "1 tablespoon sugar or honey (optional)",
    ],
    steps: [
      "Peel and chop the mangoes.",
      "Blend the mango pieces with water or coconut water.",
      "Add sugar or honey if desired, and blend until smooth.",
      "Serve chilled with ice cubes.",
    ],
    instructions:
      "A tropical, creamy juice made from ripe mangoes, perfect for a sweet, refreshing drink.",
    image: "mango juice.jpg",
  },
  {
    name: "Pineapple Juice",
    ingredients: [
      "1 fresh pineapple",
      "1 tablespoon sugar or honey (optional)",
      "1 cup water",
    ],
    steps: [
      "Peel and chop the pineapple into chunks.",
      "Blend the pineapple with water until smooth.",
      "Strain to remove the pulp (optional).",
      "Add sugar or honey to taste, and serve chilled.",
    ],
    instructions:
      "A sweet and tangy juice made from fresh pineapple, perfect for a tropical twist.",
    image: "pineapple juice.jpg",
  },
  {
    name: "Carrot Juice",
    ingredients: [
      "4-5 carrots, peeled",
      "1/2 inch ginger (optional)",
      "1 tablespoon lemon juice",
      "Honey or sugar to taste (optional)",
    ],
    steps: [
      "Wash and peel the carrots.",
      "Grate or chop them into small pieces.",
      "Blend the carrots and ginger with a little water until smooth.",
      "Add lemon juice, and sweeten with honey or sugar if desired.",
    ],
    instructions:
      "A nutritious and vibrant juice made from fresh carrots and a hint of ginger for extra flavor.",
    image: "carrot juice.jpg",
  },
  {
    name: "Watermelon Juice",
    ingredients: [
      "2 cups watermelon, cubed",
      "1/2 tablespoon lime juice",
      "Ice cubes (optional)",
    ],
    steps: [
      "Cut the watermelon into cubes and remove the seeds.",
      "Blend the watermelon until smooth.",
      "Add lime juice for extra tang, and serve chilled with ice cubes.",
    ],
    instructions:
      "A hydrating and refreshing juice made from fresh watermelon, perfect for hot summer days.",
    image: "watermelon juice.jpg",
  },
  {
    name: "Beetroot Juice",
    ingredients: [
      "1 beetroot, peeled and chopped",
      "1 carrot (optional)",
      "1/2 apple (optional)",
      "1 tablespoon lemon juice",
    ],
    steps: [
      "Peel and chop the beetroot, carrot, and apple.",
      "Blend all ingredients together until smooth.",
      "Strain if necessary and serve chilled.",
    ],
    instructions:
      "A nutrient-packed juice made with beetroot, perfect for detoxification and boosting stamina.",
    image: "beetroot juice.jpg",
  },
  {
    name: "Chocolate Milkshake",
    ingredients: [
      "2 cups cold milk",
      "3 tablespoons chocolate syrup",
      "1 scoop vanilla ice cream",
      "Whipped cream for topping",
    ],
    steps: [
      "Blend the cold milk, chocolate syrup, and ice cream until smooth.",
      "Pour into a glass and top with whipped cream.",
      "Serve immediately with a straw.",
    ],
    instructions:
      "A creamy and indulgent milkshake made with chocolate syrup and vanilla ice cream, perfect for a dessert drink.",
    image: "chocolate milkshake.jpg",
  },
  {
    name: "Vanilla Milkshake",
    ingredients: [
      "2 cups cold milk",
      "1 scoop vanilla ice cream",
      "1 tablespoon vanilla extract",
      "Whipped cream for topping",
    ],
    steps: [
      "Blend cold milk, vanilla ice cream, and vanilla extract until smooth.",
      "Pour into a glass and top with whipped cream.",
      "Serve with a straw.",
    ],
    instructions:
      "A classic and creamy vanilla milkshake made with vanilla ice cream and milk, perfect for a sweet treat.",
    image: "vanilla milkshake.jpg",
  },
  {
    name: "Strawberry Milkshake",
    ingredients: [
      "2 cups cold milk",
      "1 cup fresh strawberries",
      "1 scoop vanilla ice cream",
      "1 tablespoon sugar (optional)",
    ],
    steps: [
      "Blend cold milk, strawberries, vanilla ice cream, and sugar until smooth.",
      "Pour into a glass and serve chilled.",
    ],
    instructions:
      "A sweet and creamy milkshake made with fresh strawberries and ice cream.",
    image: "strawberry milkshake.jpg",
  },

  {
    name: "Banana Milkshake",
    ingredients: [
      "2 cups cold milk",
      "1 ripe banana",
      "1 scoop vanilla ice cream",
      "Honey or sugar to taste",
    ],
    steps: [
      "Blend the cold milk, banana, and vanilla ice cream until smooth.",
      "Add honey or sugar if you prefer a sweeter taste.",
      "Serve chilled.",
    ],
    instructions:
      "A delicious and nutritious milkshake made with ripe bananas and ice cream.",
    image: "banana milkshake.jpg",
  },
  {
    name: "Mango Milkshake",
    ingredients: [
      "1 ripe mango, peeled and chopped",
      "2 cups cold milk",
      "1 scoop vanilla ice cream",
      "Honey or sugar to taste",
    ],
    steps: [
      "Blend the mango, cold milk, and vanilla ice cream until smooth.",
      "Sweeten with honey or sugar if desired.",
      "Serve chilled.",
    ],
    instructions:
      "A tropical and creamy milkshake made with ripe mangoes and ice cream, perfect for summer.",
    image: "mango milkshake.jpg",
  },
  {
    name: "Almond Milkshake",
    ingredients: [
      "1/4 cup almonds (soaked overnight)",
      "2 cups cold milk",
      "1 scoop vanilla ice cream",
      "Honey to taste",
    ],
    steps: [
      "Soak almonds overnight and blend with cold milk until smooth.",
      "Add vanilla ice cream and blend again.",
      "Sweeten with honey, and serve chilled.",
    ],
    instructions:
      "A healthy and rich milkshake made with almonds, perfect for a nutritious snack.",
    image: "almond milkshake.jpg",
  },
  {
    name: "Anjeer Milkshake",
    ingredients: [
      "6-7 dried figs (anjeer), soaked overnight",
      "2 cups cold milk",
      "1 tablespoon honey (optional)",
      "Crushed ice (optional)",
    ],
    steps: [
      "Soak the dried figs in warm water overnight.",
      "Blend the soaked figs with cold milk until smooth.",
      "Add honey if you prefer a sweeter taste.",
      "Serve chilled with crushed ice.",
    ],
    instructions:
      "A nutritious milkshake made with anjeer (figs), perfect for boosting energy and health.",
    image: "anjeer milkshake.jpg",
  },
  {
    name: "Dryfruit Milkshake",
    ingredients: [
      "1/4 cup almonds",
      "1/4 cup cashews",
      "1/4 cup walnuts",
      "1 cup cold milk",
      "1 tablespoon honey or sugar",
      "1/4 teaspoon cardamom powder",
    ],
    steps: [
      "Soak almonds, cashews, and walnuts overnight in warm water.",
      "Blend the soaked dry fruits with cold milk until smooth.",
      "Add honey or sugar and cardamom powder, and blend again.",
      "Serve chilled.",
    ],
    instructions:
      "A rich and healthy milkshake made with a variety of dry fruits, great for energy and nutrition.",
    image: "dryfruit juice 1.jpg",
  },
  {
    name: "Chickoo Milkshake",
    ingredients: [
      "2-3 ripe chickoos (sapodillas), peeled and chopped",
      "1 cup cold milk",
      "1 tablespoon sugar or honey (optional)",
      "Ice cubes",
    ],
    steps: [
      "Peel and chop the ripe chickoos.",
      "Blend the chickoo pieces with cold milk until smooth.",
      "Add sugar or honey for sweetness and blend again.",
      "Serve chilled with ice cubes.",
    ],
    instructions:
      "A delicious milkshake made with sweet and flavorful chickoos, perfect for a nutritious treat.",
    image: "chicko milkshake.jpg",
  },
  {
    name: "Sitafal Milkshake",
    ingredients: [
      "1 sitafal (custard apple), peeled and scooped",
      "1 cup cold milk",
      "1 tablespoon sugar or honey (optional)",
      "Ice cubes",
    ],
    steps: [
      "Peel and scoop the pulp of the sitafal.",
      "Blend the custard apple pulp with cold milk until smooth.",
      "Add sugar or honey for extra sweetness, and blend again.",
      "Serve chilled with ice cubes.",
    ],
    instructions:
      "A creamy milkshake made with the sweet and tangy flavor of sitafal, perfect for a refreshing snack.",
    image: "sitafal juice.jpg",
  },
  {
    name: "Oreo Milkshake",
    ingredients: [
      "4-5 Oreo cookies",
      "2 cups cold milk",
      "1 scoop vanilla ice cream",
      "1 tablespoon chocolate syrup",
      "Whipped cream (optional)",
    ],
    steps: [
      "Blend the Oreo cookies with cold milk until smooth.",
      "Add vanilla ice cream and chocolate syrup, then blend again.",
      "Pour into a glass and top with whipped cream if desired.",
    ],
    instructions:
      "A rich and indulgent milkshake made with Oreo cookies, perfect for a chocolate lover.",
    image: "oreo milkshake.jpg",
  },
  {
    name: "Kitkat Milkshake",
    ingredients: [
      "3-4 Kitkat bars, chopped",
      "2 cups cold milk",
      "1 scoop vanilla ice cream",
      "Whipped cream (optional)",
    ],
    steps: [
      "Chop the Kitkat bars into small pieces.",
      "Blend the Kitkat pieces with cold milk and vanilla ice cream until smooth.",
      "Serve in a glass topped with whipped cream.",
    ],
    instructions:
      "A crunchy and creamy milkshake made with Kitkat bars, great for chocolate fans.",
    image: "kitkat milkshake.jpg",
  },
  {
    name: "Dairy Milk Chocolate Milkshake",
    ingredients: [
      "2-3 Dairy Milk chocolate bars",
      "2 cups cold milk",
      "1 scoop vanilla ice cream",
      "Whipped cream (optional)",
    ],
    steps: [
      "Melt the Dairy Milk chocolate bars in a microwave or double boiler.",
      "Blend the melted chocolate with cold milk and vanilla ice cream until smooth.",
      "Pour into a glass and top with whipped cream.",
    ],
    instructions:
      "A rich and creamy milkshake made with Dairy Milk chocolate, perfect for those who love chocolate.",
    image: "diary milk milkshake.jpg",
  },
  {
    name: "Cold Coffee",
    ingredients: [
      "1 cup strong brewed coffee, cooled",
      "1 cup cold milk",
      "1-2 tablespoons sugar",
      "Ice cubes",
      "Whipped cream (optional)",
    ],
    steps: [
      "Brew strong coffee and allow it to cool.",
      "Blend the coffee with cold milk and sugar until smooth.",
      "Serve in a glass with ice cubes and top with whipped cream.",
    ],
    instructions:
      "A refreshing iced coffee drink, perfect for cooling down on a warm day and energizing yourself.",
    image: "cold coffee.jpg",
  },
  {
    name: "Rooh Afza Milk",
    ingredients: [
      "1-2 tablespoons Rooh Afza syrup",
      "1 cup cold milk",
      "Ice cubes",
    ],
    steps: [
      "Add Rooh Afza syrup to cold milk and stir well.",
      "Serve chilled with ice cubes.",
    ],
    instructions:
      "A refreshing milk drink flavored with the fragrant and sweet Rooh Afza syrup, perfect for a cool treat.",
    image: "rooh afza milk.jpg",
  },
  {
    name: "Lemon Soda",
    ingredients: [
      "1/4 cup fresh lemon juice",
      "1 cup soda water",
      "1 tablespoon sugar or honey (optional)",
      "Pinch of black salt (optional)",
      "Ice cubes",
    ],
    steps: [
      "Mix lemon juice, sugar/honey, and black salt in a glass.",
      "Add soda water and stir gently.",
      "Serve chilled with ice cubes.",
    ],
    instructions:
      "A zesty and fizzy drink made with fresh lemon juice and soda water, perfect for a refreshing boost.",
    image: "lemon soda.jpg",
  },
  {
    name: "Ginger Lemon Soda",
    ingredients: [
      "1/2 inch fresh ginger, grated",
      "1/4 cup fresh lemon juice",
      "1 tablespoon honey or sugar",
      "1 cup soda water",
      "Ice cubes",
    ],
    steps: [
      "Grate the fresh ginger and squeeze out the juice.",
      "In a glass, mix ginger juice, lemon juice, and honey or sugar.",
      "Add soda water and stir gently.",
      "Serve chilled with ice cubes.",
    ],
    instructions:
      "A refreshing and spicy lemon soda with a kick of ginger, ideal for digestion and revitalization.",
    image: "lemon ginger soda.jpg",
  },
  {
    name: "Kala Khatta Soda",
    ingredients: [
      "1/4 cup kala khatta syrup (available in stores)",
      "1 cup soda water",
      "1 tablespoon lemon juice",
      "A pinch of black salt",
      "Ice cubes",
    ],
    steps: [
      "In a glass, add kala khatta syrup and lemon juice.",
      "Pour soda water over it and mix well.",
      "Add a pinch of black salt for extra flavor.",
      "Serve chilled with ice cubes.",
    ],
    instructions:
      "A popular Indian street drink made with kala khatta syrup, offering a tangy, sweet, and spicy flavor.",
    image: "kala kattha soda.jpg",
  },

  {
    name: "Rice Kheer",
    ingredients: [
      "1/4 cup basmati rice",
      "4 cups full-fat milk",
      "1/2 cup sugar",
      "1/4 teaspoon cardamom powder",
      "1 tablespoon chopped almonds and cashews",
      "1 tablespoon raisins",
      "A few saffron strands (optional)",
    ],
    steps: [
      "Rinse the rice and soak for 15 minutes.",
      "In a pan, bring milk to a boil, then reduce the heat.",
      "Add soaked rice and cook on low flame, stirring occasionally.",
      "Once the rice is cooked and the milk has thickened, add sugar and mix well.",
      "Cook for a few more minutes until the sugar dissolves completely.",
      "Add cardamom powder, chopped nuts, raisins, and saffron (if using).",
      "Serve warm or chilled.",
    ],
    instructions:
      "A creamy, aromatic dessert made with rice, milk, and sugar, garnished with dry fruits.",
    image: "rice kheer.jpg",
  },
  {
    name: "Seviyan Kheer",
    ingredients: [
      "1/4 cup seviyan (vermicelli)",
      "4 cups full-fat milk",
      "1/2 cup sugar",
      "1/4 teaspoon cardamom powder",
      "1 tablespoon chopped almonds and cashews",
      "1 tablespoon raisins",
      "A few saffron strands (optional)",
    ],
    steps: [
      "Roast the seviyan in a little ghee until golden brown.",
      "In a pan, bring milk to a boil, then add the roasted seviyan.",
      "Cook on low heat until the seviyan are soft and the milk thickens.",
      "Add sugar and cook for a few more minutes until the sugar dissolves.",
      "Add cardamom powder, nuts, raisins, and saffron.",
      "Serve warm or chilled.",
    ],
    instructions:
      "A rich and creamy dessert made with roasted vermicelli, milk, and sugar, garnished with dry fruits.",
    image: "seviyan kheer.jpg",
  },
  {
    name: "Carrot Kheer",
    ingredients: [
      "2 cups grated carrots",
      "4 cups full-fat milk",
      "1/2 cup sugar",
      "1/4 teaspoon cardamom powder",
      "1 tablespoon chopped almonds and cashews",
      "1 tablespoon raisins",
      "A few saffron strands (optional)",
    ],
    steps: [
      "In a pan, cook grated carrots with a little water until soft.",
      "Add milk and cook the mixture until it thickens and the milk is absorbed.",
      "Add sugar and cook for a few more minutes.",
      "Add cardamom powder, nuts, raisins, and saffron (if using).",
      "Serve warm or chilled.",
    ],
    instructions:
      "A sweet and aromatic kheer made with grated carrots and milk, enriched with dry fruits.",
    image: "carrot kheer.jpg",
  },
  {
    name: "Sago Kheer",
    ingredients: [
      "1/4 cup sago (sabudana)",
      "4 cups full-fat milk",
      "1/2 cup sugar",
      "1/4 teaspoon cardamom powder",
      "1 tablespoon chopped almonds and cashews",
      "1 tablespoon raisins",
    ],
    steps: [
      "Wash and soak the sabudana for 30 minutes.",
      "In a pan, bring milk to a boil and cook the soaked sabudana until soft.",
      "Add sugar and cook for a few more minutes.",
      "Add cardamom powder, nuts, and raisins.",
      "Serve warm or chilled.",
    ],
    instructions:
      "A creamy kheer made with sabudana (sago pearls) and milk, flavored with cardamom and garnished with dry fruits.",
    image: "sabudana kheer.jpg",
  },
  {
    name: "Veg Biryani",
    ingredients: [
      "2 cups basmati rice",
      "1 cup mixed vegetables (carrot, beans, peas, potatoes)",
      "1 large onion, thinly sliced",
      "2 tomatoes, chopped",
      "1/4 cup yogurt",
      "1/4 cup mint leaves",
      "1/4 cup coriander leaves",
      "1 teaspoon ginger-garlic paste",
      "1/4 teaspoon turmeric powder",
      "1 teaspoon red chili powder",
      "1 teaspoon garam masala",
      "1 cinnamon stick",
      "2-3 cloves",
      "2-3 green cardamoms",
      "1 bay leaf",
      "1 tablespoon ghee",
      "2 tablespoons oil",
      "Salt to taste",
      "Water as needed",
    ],
    steps: [
      "Rinse the rice and soak for 20 minutes.",
      "Heat oil and ghee in a pan, add whole spices (cinnamon, cloves, cardamom, bay leaf), and sauté for a minute.",
      "Add onions and sauté until golden brown. Add ginger-garlic paste and sauté for another minute.",
      "Add tomatoes, turmeric, chili powder, garam masala, and salt. Cook until tomatoes soften.",
      "Add mixed vegetables and cook for 5-6 minutes. Stir in yogurt, mint, and coriander leaves.",
      "Add soaked rice and enough water (1.5-2 cups) for cooking. Cook on low heat, covered, until rice is cooked.",
      "Serve hot with raita or salad.",
    ],
    instructions:
      "A fragrant and flavorful rice dish made with mixed vegetables, rice, and aromatic spices.",
    image: "veg biryani.jpg",
  },
  {
    name: "Chicken Biryani",
    ingredients: [
      "2 cups basmati rice",
      "500g chicken pieces",
      "2 large onions, thinly sliced",
      "2 tomatoes, chopped",
      "1/4 cup yogurt",
      "1/4 cup mint leaves",
      "1/4 cup coriander leaves",
      "1 tablespoon ginger-garlic paste",
      "1/4 teaspoon turmeric powder",
      "1 teaspoon red chili powder",
      "1 teaspoon garam masala",
      "1 cinnamon stick",
      "2-3 cloves",
      "2-3 green cardamoms",
      "1 bay leaf",
      "1 tablespoon ghee",
      "2 tablespoons oil",
      "Salt to taste",
      "Water as needed",
    ],
    steps: [
      "Rinse the rice and soak for 20 minutes.",
      "Heat oil and ghee in a pan, add whole spices (cinnamon, cloves, cardamom, bay leaf), and sauté for a minute.",
      "Add onions and sauté until golden brown. Add ginger-garlic paste and sauté for another minute.",
      "Add tomatoes, turmeric, chili powder, garam masala, and salt. Cook until tomatoes soften.",
      "Add chicken pieces and cook until they are browned and cooked through.",
      "Add yogurt, mint, and coriander leaves, and simmer for a few minutes.",
      "In a separate pan, cook the soaked rice with enough water until it is 70% cooked.",
      "Layer the rice over the chicken, sprinkle with mint and coriander leaves, and cook on low heat, covered, for 15-20 minutes.",
      "Serve hot with raita or salad.",
    ],
    instructions:
      "A rich and spicy rice dish with marinated chicken, aromatic spices, and basmati rice.",
    image: "chicken biryani.jpg",
  },
  {
    name: "Mutton Biryani",
    ingredients: [
      "2 cups basmati rice",
      "500g mutton (goat or lamb), cut into pieces",
      "2 large onions, thinly sliced",
      "2 tomatoes, chopped",
      "1/4 cup yogurt",
      "1/4 cup mint leaves",
      "1/4 cup coriander leaves",
      "1 tablespoon ginger-garlic paste",
      "1/4 teaspoon turmeric powder",
      "1 teaspoon red chili powder",
      "1 teaspoon garam masala",
      "1 cinnamon stick",
      "2-3 cloves",
      "2-3 green cardamoms",
      "1 bay leaf",
      "1 tablespoon ghee",
      "2 tablespoons oil",
      "Salt to taste",
      "Water as needed",
    ],
    steps: [
      "Rinse the rice and soak for 20 minutes.",
      "In a pressure cooker, heat oil and ghee, add whole spices (cinnamon, cloves, cardamom, bay leaf), and sauté for a minute.",
      "Add onions and sauté until golden brown. Add ginger-garlic paste and sauté for another minute.",
      "Add tomatoes, turmeric, chili powder, garam masala, and salt. Cook until tomatoes soften.",
      "Add mutton pieces and cook until browned. Add yogurt, mint, and coriander leaves, and cook for 10-12 minutes.",
      "In a separate pan, cook the soaked rice with enough water until 70% cooked.",
      "Layer the rice over the mutton, sprinkle with mint and coriander leaves, and cook on low heat for 30-40 minutes.",
      "Serve hot with raita or salad.",
    ],
    instructions:
      "A fragrant and rich rice dish made with tender mutton, aromatic spices, and basmati rice.",
    image: "mutton biryani.jpg",
  },
  {
    name: "Arabian Mandi",
    ingredients: [
      "2 cups basmati rice",
      "500g chicken or mutton pieces",
      "2 large onions, chopped",
      "2 tomatoes, chopped",
      "1 tablespoon ginger-garlic paste",
      "1/4 teaspoon turmeric powder",
      "1 teaspoon cumin powder",
      "1 teaspoon coriander powder",
      "1 teaspoon garam masala",
      "1 cinnamon stick",
      "2-3 cloves",
      "2-3 green cardamoms",
      "2-3 bay leaves",
      "2 tablespoons oil",
      "Salt to taste",
      "Water as needed",
      "Few strands of saffron (optional)",
    ],
    steps: [
      "Rinse the rice and soak for 20 minutes.",
      "Heat oil in a large pot and sauté onions until golden brown.",
      "Add ginger-garlic paste and sauté for a minute. Add tomatoes and cook until soft.",
      "Add all spices (turmeric, cumin, coriander, garam masala) and salt, and cook for 2-3 minutes.",
      "Add chicken or mutton pieces, sauté, and cook until browned.",
      "Add water and let it simmer until the meat is tender.",
      "In a separate pan, cook the rice with enough water and saffron (if using) until 70% cooked.",
      "Layer the rice on top of the meat, cover, and cook on low heat for 20-30 minutes.",
      "Serve hot with yogurt or a fresh salad.",
    ],
    instructions:
      "A fragrant Arabian dish made with spiced rice and meat (chicken or mutton), cooked to perfection with aromatic spices.",
    image: "arabian mandi.jpg",
  },
  {
    name: "Chicken Mandi",
    ingredients: [
      "2 cups basmati rice",
      "500g chicken pieces",
      "2 onions, thinly sliced",
      "1 tablespoon ginger-garlic paste",
      "1/2 teaspoon turmeric powder",
      "1 teaspoon cumin powder",
      "1 teaspoon coriander powder",
      "1 teaspoon garam masala",
      "1 cinnamon stick",
      "2-3 cloves",
      "2-3 green cardamoms",
      "2 bay leaves",
      "2 tablespoons oil",
      "Salt to taste",
      "Water as needed",
    ],
    steps: [
      "Rinse the rice and soak for 20 minutes.",
      "Heat oil in a large pot, add onions, and sauté until golden brown.",
      "Add ginger-garlic paste and sauté for a minute. Add chicken and cook until browned.",
      "Add spices (turmeric, cumin, coriander, garam masala) and salt, cook for a few minutes.",
      "Add water and cook until the chicken is tender and the flavors are well combined.",
      "In a separate pot, cook the rice until 70% done.",
      "Layer the rice over the chicken, cover, and cook on low heat for 20-30 minutes.",
      "Serve with salad or yogurt.",
    ],
    instructions:
      "A fragrant dish made with rice, chicken, and aromatic spices, cooked in a traditional Arabian style.",
    image: "chicken mandi.jpg",
  },
  {
    name: "Mutton Mandi",
    ingredients: [
      "2 cups basmati rice",
      "500g mutton pieces",
      "2 large onions, chopped",
      "1 tablespoon ginger-garlic paste",
      "1/2 teaspoon turmeric powder",
      "1 teaspoon cumin powder",
      "1 teaspoon coriander powder",
      "1 teaspoon garam masala",
      "1 cinnamon stick",
      "2-3 cloves",
      "2-3 green cardamoms",
      "2 bay leaves",
      "2 tablespoons oil",
      "Salt to taste",
      "Water as needed",
    ],
    steps: [
      "Rinse the rice and soak for 20 minutes.",
      "In a pot, heat oil and sauté onions until golden brown.",
      "Add ginger-garlic paste, cook for a minute, then add mutton pieces.",
      "Add spices (turmeric, cumin, coriander, garam masala) and salt, cook for 10-12 minutes.",
      "Add water, cook until the mutton is tender and the flavors are well combined.",
      "In a separate pan, cook the rice until 70% done.",
      "Layer the rice over the mutton and cook on low heat for 30 minutes.",
      "Serve with raita or a salad.",
    ],
    instructions:
      "A rich and flavorful dish made with tender mutton and basmati rice, infused with spices.",
    image: "mutton mandi 1.jpg",
  },
  {
    name: "Gajar ka Halwa (Carrot Halwa)",
    ingredients: [
      "4-5 medium-sized carrots (grated)",
      "2 cups full-fat milk",
      "1/2 cup sugar (adjust to taste)",
      "2 tablespoons ghee (clarified butter)",
      "1/4 cup chopped nuts (cashews, almonds, or pistachios)",
      "1/4 teaspoon cardamom powder",
      "A pinch of saffron strands (optional)",
      "1 tablespoon raisins (optional)",
    ],
    steps: [
      "Wash, peel, and grate the carrots using a box grater or food processor.",
      "In a heavy-bottomed pan, add the grated carrots and 2 cups of milk.",
      "Cook on medium heat, stirring occasionally, until the milk is reduced by about 75% and the carrots soften (around 15-20 minutes).",
      "Once the milk is mostly absorbed, add 2 tablespoons of ghee and cook for 5-7 minutes.",
      "Add sugar and stir well. Continue to cook until the mixture thickens and the ghee starts to separate from the halwa (about 10-15 minutes).",
      "Add cardamom powder, chopped nuts, and raisins (if using). Stir everything together and cook for another 2-3 minutes.",
      "Garnish with extra nuts or saffron strands if desired. Serve warm as a delightful dessert.",
    ],
    instructions:
      "Gajar ka Halwa, or Carrot Halwa, is a rich, flavorful Indian dessert made with grated carrots, milk, sugar, and ghee. It’s a comforting treat often served during festivals or special occasions.",
    image: "gajar ka halwa.jpg",
  },
];
