// recipe2.js
export const recipe2 = [
  {
    name: "Chicken Curry",
    ingredients: [
      "500g chicken, cut into pieces",
      "1 onion, chopped",
      "2 tomatoes, chopped",
      "2 tbsp curry powder",
      "1 tbsp ginger-garlic paste",
      "1 cup coconut milk",
      "Salt to taste",
      "1 tbsp oil",
      "Fresh coriander leaves for garnish",
    ],
    steps: [
      "Heat oil in a pan, add onions and cook until golden brown.",
      "Add ginger-garlic paste and cook for a minute.",
      "Add chicken pieces and cook until browned.",
      "Add chopped tomatoes and cook for 5 minutes until softened.",
      "Add curry powder and mix well.",
      "Pour in coconut milk, add salt, and cook on low heat for 20 minutes.",
      "Garnish with fresh coriander leaves.",
    ],
    instructions:
      "A flavorful chicken curry with coconut milk, perfect for a comforting meal.",
    image: "chicken curry.png",
  },
  {
    name: "Chicken Kabab",
    ingredients: [
      "500g boneless chicken, cut into pieces",
      "1/2 cup yogurt",
      "1 tablespoon ginger-garlic paste",
      "1 teaspoon red chili powder",
      "1 teaspoon turmeric powder",
      "1 teaspoon garam masala",
      "1 tablespoon lemon juice",
      "Salt to taste",
      "Fresh coriander leaves, chopped",
      "Skewers (metal or wooden)",
    ],
    steps: [
      "In a bowl, mix the yogurt, ginger-garlic paste, red chili powder, turmeric powder, garam masala, lemon juice, and salt.",
      "Add the chicken pieces to the marinade and mix well. Let it marinate for at least 1 hour (overnight is best).",
      "Preheat the grill or oven to 200°C (400°F). If using wooden skewers, soak them in water for 30 minutes.",
      "Thread the marinated chicken pieces onto the skewers and place them on the grill or in the oven.",
      "Cook the kababs for 20-25 minutes, turning occasionally, until they are cooked through and slightly charred.",
      "Garnish with fresh coriander leaves and serve with mint chutney.",
    ],
    instructions:
      "A flavorful and smoky chicken dish cooked on skewers, perfect for appetizers or a party.",
    image: "chciken kabab.jpg",
  },
  {
    name: "Chicken 65",
    ingredients: [
      "500g boneless chicken, cut into small cubes",
      "1 tablespoon ginger-garlic paste",
      "1 teaspoon red chili powder",
      "1 teaspoon turmeric powder",
      "1 teaspoon cumin powder",
      "1/2 teaspoon garam masala",
      "1 tablespoon lemon juice",
      "Salt to taste",
      "2 tablespoons rice flour",
      "2 tablespoons corn flour",
      "Oil for deep frying",
      "Fresh curry leaves",
    ],
    steps: [
      "In a bowl, mix ginger-garlic paste, red chili powder, turmeric powder, cumin powder, garam masala, lemon juice, salt, rice flour, and corn flour to form a thick batter.",
      "Add the chicken cubes to the batter and marinate for 30 minutes.",
      "Heat oil in a pan and deep fry the marinated chicken until golden brown and crispy.",
      "In a separate pan, heat a little oil, and sauté fresh curry leaves for a minute.",
      "Add the fried chicken to the pan and toss it well in the curry leaves.",
      "Serve hot as a spicy appetizer or snack.",
    ],
    instructions:
      "A spicy, crispy, and flavorful deep-fried chicken snack originating from South India.",
    image: "chicken 65.jpg",
  },
  {
    name: "Chicken Manchurian",
    ingredients: [
      "500g boneless chicken, cut into bite-sized pieces",
      "1 tablespoon ginger-garlic paste",
      "1 onion, finely chopped",
      "1 bell pepper, chopped",
      "2-3 tablespoons soy sauce",
      "1 tablespoon chili sauce",
      "1 tablespoon tomato ketchup",
      "1/2 teaspoon black pepper powder",
      "1/4 teaspoon turmeric powder",
      "2 tablespoons corn flour",
      "1/2 cup water",
      "Oil for frying",
      "Spring onions for garnish",
    ],
    steps: [
      "In a bowl, mix chicken pieces with corn flour, black pepper, and a pinch of salt to coat the chicken.",
      "Heat oil in a pan and fry the chicken pieces until golden and crispy. Set aside.",
      "In the same pan, sauté ginger-garlic paste, onion, and bell pepper until softened.",
      "Add soy sauce, chili sauce, tomato ketchup, and turmeric powder. Stir well and add water to make a sauce.",
      "Add the fried chicken pieces to the sauce and toss well to coat the chicken evenly.",
      "Garnish with spring onions and serve hot with fried rice or noodles.",
    ],
    instructions:
      "A Chinese-inspired, sweet and spicy chicken dish that is crispy on the outside and coated in a flavorful sauce.",
    image: "chicken manchurian.jpg",
  },
  {
    name: "Chicken Chilli",
    ingredients: [
      "500g boneless chicken, cut into strips",
      "1 tablespoon ginger-garlic paste",
      "1 onion, sliced",
      "1 green bell pepper, sliced",
      "2-3 green chilies, chopped",
      "2 tablespoons soy sauce",
      "1 tablespoon chili sauce",
      "1 teaspoon vinegar",
      "1 tablespoon corn flour",
      "Salt and pepper to taste",
      "Oil for frying",
      "Fresh coriander leaves for garnish",
    ],
    steps: [
      "Marinate chicken strips with soy sauce, chili sauce, vinegar, and corn flour for 20-30 minutes.",
      "Heat oil in a pan and fry the marinated chicken strips until crispy. Remove and set aside.",
      "In the same pan, sauté ginger-garlic paste, onion, bell pepper, and green chilies until soft.",
      "Add fried chicken to the pan, and toss well with the veggies.",
      "Season with salt and pepper, and cook for another 2-3 minutes.",
      "Garnish with fresh coriander leaves and serve hot.",
    ],
    instructions:
      "A spicy, tangy chicken dish with crispy chicken strips stir-fried with vegetables and a flavorful sauce.",
    image: "chicken chilli.jpg",
  },
  {
    name: "Tandoori Chicken",
    ingredients: [
      "1 whole chicken (cut into pieces)",
      "1/2 cup yogurt",
      "2 tablespoons tandoori masala",
      "1 tablespoon ginger-garlic paste",
      "1 teaspoon red chili powder",
      "1 teaspoon cumin powder",
      "1 tablespoon lemon juice",
      "Salt to taste",
      "2 tablespoons mustard oil",
      "Fresh coriander for garnish",
    ],
    steps: [
      "In a bowl, mix yogurt, tandoori masala, ginger-garlic paste, red chili powder, cumin powder, lemon juice, salt, and mustard oil to form a smooth marinade.",
      "Coat the chicken pieces with the marinade and let it marinate for at least 2 hours or overnight for better flavor.",
      "Preheat the oven or tandoor to 200°C (400°F).",
      "Place the marinated chicken pieces on a baking tray and cook for 25-30 minutes or until the chicken is cooked through and slightly charred.",
      "Garnish with fresh coriander and serve hot with naan or rice.",
    ],
    instructions:
      "A classic Indian dish, the tandoori chicken is marinated in a spiced yogurt mixture and then grilled to perfection, creating a smoky and tender dish.",
    image: "tandoori chicken.jpg",
  },
  {
    name: "Paneer Masala",
    ingredients: [
      "250g paneer, cubed",
      "1 onion, finely chopped",
      "2 tomatoes, pureed",
      "1 tablespoon ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon garam masala",
      "1/2 teaspoon turmeric powder",
      "1 teaspoon red chili powder",
      "1/2 teaspoon cumin powder",
      "1/2 teaspoon coriander powder",
      "1/4 cup cream",
      "Salt to taste",
      "Coriander leaves for garnish",
      "2 tablespoons oil",
    ],
    steps: [
      "Heat oil in a pan, add cumin seeds and sauté for a few seconds.",
      "Add chopped onions and sauté until golden brown.",
      "Add ginger-garlic paste and cook until fragrant.",
      "Add pureed tomatoes, turmeric powder, red chili powder, cumin powder, coriander powder, and salt. Cook until the oil separates from the masala.",
      "Add water to adjust the consistency of the gravy, and cook for 5 minutes.",
      "Add cubed paneer to the gravy and stir gently.",
      "Add cream, garam masala, and cook for another 5 minutes.",
      "Garnish with fresh coriander leaves and serve hot with roti, naan, or rice.",
    ],
    instructions:
      "A rich and flavorful curry made with soft paneer cubes in a spiced tomato-based gravy, ideal for vegetarians.",
    image: "Screenshot 2024-11-12 112034.png",
  },
  {
    name: "Butter Chicken",
    ingredients: [
      "500g boneless chicken, cut into pieces",
      "1/2 cup yogurt",
      "1 tablespoon ginger-garlic paste",
      "1 tablespoon lemon juice",
      "1 teaspoon red chili powder",
      "1 teaspoon garam masala",
      "1/2 teaspoon turmeric powder",
      "1 tablespoon butter",
      "1 onion, finely chopped",
      "2 tomatoes, pureed",
      "1/2 cup cream",
      "1 teaspoon sugar",
      "Salt to taste",
      "Fresh coriander for garnish",
    ],
    steps: [
      "Marinate the chicken with yogurt, ginger-garlic paste, lemon juice, red chili powder, garam masala, turmeric powder, and salt. Let it marinate for at least 1 hour.",
      "Heat butter in a pan, and sauté chopped onions until golden brown.",
      "Add pureed tomatoes, sugar, and cook until the oil separates from the masala.",
      "Add the marinated chicken pieces and cook for 10-15 minutes, until the chicken is cooked through.",
      "Add cream and stir to make a rich, creamy gravy.",
      "Simmer for 5 more minutes, then garnish with fresh coriander.",
      "Serve with naan or rice.",
    ],
    instructions:
      "A creamy, indulgent North Indian dish made with tender chicken pieces simmered in a rich, buttery tomato gravy.",
    image: "butter chicken.jpg",
  },
  {
    name: "Butter Paneer",
    ingredients: [
      "250g paneer, cubed",
      "2 tablespoons butter",
      "1 onion, finely chopped",
      "1 tablespoon ginger-garlic paste",
      "2 tomatoes, pureed",
      "1/2 cup cream",
      "1 teaspoon red chili powder",
      "1 teaspoon garam masala",
      "1/2 teaspoon cumin powder",
      "1/2 teaspoon turmeric powder",
      "Salt to taste",
      "Fresh coriander leaves for garnish",
    ],
    steps: [
      "Heat butter in a pan and sauté chopped onions until golden brown.",
      "Add ginger-garlic paste and cook for a minute until fragrant.",
      "Add pureed tomatoes, red chili powder, garam masala, cumin powder, turmeric powder, and salt. Cook for 10 minutes until the oil separates from the masala.",
      "Add cubed paneer to the pan and stir gently to coat with the masala.",
      "Add cream to make the gravy creamy and simmer for 5-7 minutes.",
      "Garnish with fresh coriander leaves and serve hot with naan or rice.",
    ],
    instructions:
      "A rich, buttery, and creamy dish with soft paneer cubes cooked in a flavorful tomato-based gravy.",
    image: "butter paneer.jpg",
  },
  {
    name: "Chicken Soup",
    ingredients: [
      "500g chicken (with bones, cut into pieces)",
      "1 onion, chopped",
      "1 carrot, chopped",
      "1 celery stalk, chopped",
      "2 garlic cloves, minced",
      "1 bay leaf",
      "Salt and pepper to taste",
      "6 cups chicken broth or water",
      "1 teaspoon thyme",
      "Fresh parsley for garnish",
    ],
    steps: [
      "In a large pot, add chicken pieces, water, onion, carrot, celery, garlic, and bay leaf.",
      "Bring to a boil, then reduce heat and let it simmer for 30-40 minutes until the chicken is cooked and tender.",
      "Remove the chicken, discard bones, and shred the meat.",
      "Return the shredded chicken to the pot, add thyme, salt, and pepper.",
      "Simmer for another 10 minutes.",
      "Garnish with fresh parsley and serve hot.",
    ],
    instructions:
      "A comforting and hearty soup made with tender chicken and vegetables, perfect for a cold day.",
    image: "chicken soup.jpg",
  },
  {
    name: "Veg Soup",
    ingredients: [
      "1 onion, chopped",
      "1 carrot, chopped",
      "1 potato, peeled and chopped",
      "1 zucchini, chopped",
      "1 celery stalk, chopped",
      "2 tomatoes, chopped",
      "1 cup green beans, chopped",
      "6 cups vegetable broth or water",
      "1 teaspoon garlic powder",
      "1 teaspoon thyme",
      "Salt and pepper to taste",
      "Olive oil for cooking",
      "Fresh basil for garnish",
    ],
    steps: [
      "Heat olive oil in a large pot and sauté onions, carrots, potatoes, zucchini, and celery for 5-7 minutes.",
      "Add tomatoes, green beans, vegetable broth, garlic powder, thyme, salt, and pepper.",
      "Bring to a boil, then reduce heat and simmer for 30 minutes until the vegetables are tender.",
      "Adjust seasoning to taste and serve hot, garnished with fresh basil.",
    ],
    instructions:
      "A light and nutritious vegetable soup made with a mix of fresh vegetables, perfect for a healthy meal.",
    image: "veg soup.jpg",
  },
  {
    name: "Egg Soup",
    ingredients: [
      "2 eggs, beaten",
      "1 onion, chopped",
      "1 carrot, chopped",
      "1 stalk celery, chopped",
      "4 cups chicken or vegetable broth",
      "1 teaspoon soy sauce",
      "Salt and pepper to taste",
      "Chopped green onions for garnish",
    ],
    steps: [
      "Heat the broth in a large pot and bring it to a simmer.",
      "Add chopped onions, carrots, and celery, and cook until the vegetables are tender, about 10 minutes.",
      "Slowly pour in the beaten eggs, stirring constantly to create egg ribbons.",
      "Add soy sauce, salt, and pepper, and cook for 2-3 more minutes.",
      "Garnish with chopped green onions and serve hot.",
    ],
    instructions:
      "A quick and easy soup made with beaten eggs, vegetables, and a flavorful broth, perfect for a light meal.",
    image: "egg soup.jpg",
  },
  {
    name: "Orange Juice",
    ingredients: [
      "4-5 fresh oranges",
      "1 teaspoon sugar (optional)",
      "Ice cubes (optional)",
    ],
    steps: [
      "Peel and segment the oranges.",
      "Blend the oranges until smooth, adding sugar if desired.",
      "Serve chilled with ice cubes if preferred.",
    ],
    instructions:
      "A refreshing juice made from freshly squeezed oranges, perfect for a nutritious start to the day.",
    image: "orange juice.jpg",
  },
  {
    name: "Veg Sandwich",
    ingredients: [
      "2 slices of bread",
      "1 tablespoon butter",
      "1/4 cup sliced cucumber",
      "1/4 cup sliced tomatoes",
      "1/4 cup sliced onions",
      "1/4 cup lettuce leaves",
      "Salt and pepper to taste",
      "1 tablespoon green chutney (optional)",
    ],
    steps: [
      "Butter both slices of bread and spread green chutney if desired.",
      "Layer cucumber, tomato, onion, and lettuce on one slice of bread.",
      "Sprinkle with salt and pepper.",
      "Place the second slice on top, cut into halves, and serve.",
    ],
    instructions:
      "A quick, fresh, and healthy veggie sandwich for a light snack.",
    image: "veg sandwich.jpg",
  },
  {
    name: "Veg Burger",
    ingredients: [
      "1 burger bun",
      "1 veggie patty",
      "1 tablespoon mayonnaise",
      "1/4 cup lettuce",
      "1 slice tomato",
      "1 slice onion",
      "1 slice cheese (optional)",
    ],
    steps: [
      "Toast the burger bun lightly.",
      "Cook or heat the veggie patty according to package instructions.",
      "Spread mayonnaise on the buns and add lettuce, tomato, onion, and cheese if desired.",
      "Place the veggie patty on top, close the burger with the bun, and serve.",
    ],
    instructions:
      "A simple and delicious veg burger, customizable with your favorite toppings.",
    image: "veg burger.jpg",
  },
  {
    name: "Zinger Burger",
    ingredients: [
      "1 burger bun",
      "1 zinger-style fried chicken fillet",
      "1 tablespoon mayonnaise",
      "1/4 cup lettuce",
      "1 slice cheese (optional)",
    ],
    steps: [
      "Toast the burger bun lightly.",
      "Prepare the zinger-style chicken fillet as directed (usually involves frying with a spicy breading).",
      "Spread mayonnaise on the buns and add lettuce and cheese if desired.",
      "Place the chicken fillet on top, close the burger with the bun, and serve.",
    ],
    instructions:
      "A crispy and spicy Zinger burger with fried chicken and fresh toppings.",
    image: "zinger burger.jpg",
  },
  {
    name: "Chicken Burger",
    ingredients: [
      "1 burger bun",
      "1 grilled or fried chicken patty",
      "1 tablespoon mayonnaise",
      "1/4 cup lettuce",
      "1 slice tomato",
      "1 slice onion",
      "1 slice cheese (optional)",
    ],
    steps: [
      "Toast the burger bun lightly.",
      "Cook the chicken patty according to instructions.",
      "Spread mayonnaise on the buns and add lettuce, tomato, onion, and cheese if desired.",
      "Place the chicken patty on top, close the burger with the bun, and serve.",
    ],
    instructions:
      "A classic chicken burger with a juicy patty and fresh toppings.",
    image: "chicken burger.jpg",
  },
  {
    name: "Chicken Sandwich",
    ingredients: [
      "2 slices of bread",
      "1 tablespoon butter",
      "1/2 cup cooked shredded chicken",
      "1 tablespoon mayonnaise",
      "1/4 cup sliced cucumber",
      "1/4 cup lettuce leaves",
      "Salt and pepper to taste",
    ],
    steps: [
      "Butter both slices of bread.",
      "Mix shredded chicken with mayonnaise, salt, and pepper.",
      "Spread the chicken mixture on one slice of bread.",
      "Layer with cucumber and lettuce, then place the other slice of bread on top.",
      "Cut into halves and serve.",
    ],
    instructions: "A hearty chicken sandwich perfect for a quick meal.",
    image: "chicken sandwich.jpg",
  },
  {
    name: "Chicken Roll",
    ingredients: [
      "1 flatbread or tortilla",
      "1/2 cup cooked shredded chicken",
      "1 tablespoon mayonnaise or yogurt",
      "1/4 cup sliced onions",
      "1/4 cup sliced bell peppers",
      "Salt and pepper to taste",
    ],
    steps: [
      "Spread mayonnaise or yogurt on the flatbread.",
      "Layer shredded chicken, onions, and bell peppers on the flatbread.",
      "Season with salt and pepper.",
      "Roll tightly and serve.",
    ],
    instructions: "A delicious chicken roll with savory fillings.",
    image: "chicken roll.jpg",
  },
  {
    name: "Veg Roll",
    ingredients: [
      "1 flatbread or tortilla",
      "1/4 cup sliced cucumber",
      "1/4 cup sliced tomatoes",
      "1/4 cup shredded lettuce",
      "1 tablespoon green chutney",
      "Salt and pepper to taste",
    ],
    steps: [
      "Spread green chutney on the flatbread.",
      "Layer cucumber, tomato, and lettuce on the flatbread.",
      "Season with salt and pepper.",
      "Roll tightly and serve.",
    ],
    instructions: "A fresh and healthy veg roll with crunchy vegetables.",
    image: "veg roll.jpg",
  },
  {
    name: "Veg Pizza",
    ingredients: [
      "1 pizza base",
      "1/2 cup pizza sauce",
      "1/2 cup grated mozzarella cheese",
      "1/4 cup sliced bell peppers",
      "1/4 cup sliced onions",
      "1/4 cup sliced tomatoes",
      "1/4 cup sliced olives (optional)",
    ],
    steps: [
      "Preheat oven to 425°F (220°C).",
      "Spread pizza sauce on the pizza base.",
      "Top with mozzarella cheese, bell peppers, onions, tomatoes, and olives.",
      "Bake for 10-12 minutes or until the cheese is melted and bubbly.",
      "Remove from oven, slice, and serve.",
    ],
    instructions: "A classic veggie pizza with a variety of toppings.",
    image: "veg pizza.jpg",
  },
  {
    name: "Chicken Pizza",
    ingredients: [
      "1 pizza base",
      "1/2 cup pizza sauce",
      "1/2 cup grated mozzarella cheese",
      "1/2 cup cooked shredded chicken",
      "1/4 cup sliced bell peppers",
      "1/4 cup sliced onions",
      "1/4 cup sliced mushrooms (optional)",
    ],
    steps: [
      "Preheat oven to 425°F (220°C).",
      "Spread pizza sauce on the pizza base.",
      "Top with mozzarella cheese, shredded chicken, bell peppers, onions, and mushrooms.",
      "Bake for 10-12 minutes or until the cheese is melted and bubbly.",
      "Remove from oven, slice, and serve.",
    ],
    instructions: "A delicious chicken pizza loaded with toppings.",
    image: "chicken pizza.jpg",
  },
  {
    name: "Arabian Shawarma",
    ingredients: [
      "300g chicken breast, sliced thinly",
      "1/4 cup yogurt",
      "1 tablespoon lemon juice",
      "1 tablespoon olive oil",
      "1/2 teaspoon garlic powder",
      "1/2 teaspoon paprika",
      "1/2 teaspoon cumin powder",
      "1/2 teaspoon ground coriander",
      "Salt and pepper to taste",
      "4 pita breads",
      "1/2 cup tahini sauce",
      "1/2 cup shredded lettuce",
      "1/4 cup sliced onions",
      "1/4 cup pickles",
    ],
    steps: [
      "Marinate the chicken with yogurt, lemon juice, olive oil, garlic powder, paprika, cumin, coriander, salt, and pepper. Let it rest for 30 minutes.",
      "Cook the marinated chicken in a hot skillet until fully cooked.",
      "Spread tahini sauce on pita bread, add chicken, lettuce, onions, and pickles, and roll the pita tightly.",
      "Serve immediately.",
    ],
    instructions:
      "An authentic Arabian shawarma with marinated chicken and fresh veggies in pita bread.",
    image: "arabian shawarma.jpg",
  },
  {
    name: "Roomali Roti",
    ingredients: [
      "2 cups all-purpose flour",
      "1/4 teaspoon salt",
      "Water as needed",
      "1 tablespoon oil",
    ],
    steps: [
      "In a bowl, mix flour and salt, adding water gradually to form a soft dough. Add oil and knead for a few minutes.",
      "Cover the dough and let it rest for 20 minutes.",
      "Divide the dough into small balls and roll each into a very thin, large circle.",
      "Heat a large tawa or griddle, cook each roti for a few seconds on each side until slightly puffed and cooked.",
      "Fold and serve.",
    ],
    instructions:
      "Thin, soft Indian flatbread commonly used for wraps and kebabs.",
    image: "roomali roti.jpg",
  },
  {
    name: "Prawns Chilli",
    ingredients: [
      "250g prawns, cleaned and deveined",
      "2 tablespoons oil",
      "1/4 cup sliced onions",
      "1/4 cup bell peppers",
      "1 teaspoon ginger-garlic paste",
      "1 tablespoon soy sauce",
      "1 tablespoon chili sauce",
      "Salt and pepper to taste",
      "1/2 teaspoon sugar",
      "Spring onions for garnish",
    ],
    steps: [
      "Heat oil in a pan and sauté ginger-garlic paste.",
      "Add prawns and cook until pink, then add onions and bell peppers.",
      "Stir in soy sauce, chili sauce, salt, pepper, and sugar. Toss to coat the prawns.",
      "Garnish with spring onions and serve hot.",
    ],
    instructions:
      "A spicy, tangy prawns dish with bell peppers and chili sauce.",
    image: "prawns chilli.jpg",
  },
  {
    name: "Prawns Fry",
    ingredients: [
      "250g prawns, cleaned and deveined",
      "1 tablespoon turmeric powder",
      "1/2 teaspoon chili powder",
      "Salt to taste",
      "1 tablespoon lemon juice",
      "2 tablespoons oil",
      "Coriander leaves for garnish",
    ],
    steps: [
      "Marinate prawns with turmeric, chili powder, salt, and lemon juice for 15 minutes.",
      "Heat oil in a pan, add prawns, and fry until golden and cooked through.",
      "Garnish with coriander leaves and serve hot.",
    ],
    instructions: "Crispy fried prawns with a simple, flavorful marinade.",
    image: "prawns fry 1.jpg",
  },
  {
    name: "Prawns Biryani",
    ingredients: [
      "250g prawns, cleaned and deveined",
      "1 cup basmati rice",
      "1/2 cup yogurt",
      "1/4 cup fried onions",
      "1 tablespoon biryani masala",
      "1/2 teaspoon turmeric powder",
      "1/2 teaspoon chili powder",
      "1 tablespoon ghee",
      "Salt to taste",
      "Coriander and mint leaves for garnish",
    ],
    steps: [
      "Cook basmati rice with salt and set aside.",
      "Marinate prawns with yogurt, biryani masala, turmeric, and chili powder for 15 minutes.",
      "Heat ghee in a pot, add marinated prawns, and cook until they are half done.",
      "Layer the rice over the prawns, add fried onions, and cover. Cook on low heat for 10-15 minutes.",
      "Garnish with coriander and mint leaves before serving.",
    ],
    instructions:
      "A flavorful biryani made with juicy prawns and fragrant basmati rice.",
    image: "prawns biryani.jpg",
  },
  {
    name: "Sweet Corn",
    ingredients: [
      "2 cups fresh or canned sweet corn kernels",
      "1 tablespoon butter",
      "Salt to taste",
      "Black pepper to taste",
      "1/4 teaspoon chili powder (optional)",
      "1/4 cup grated cheese (optional)",
      "1 tablespoon chopped fresh parsley or coriander (optional)",
    ],
    steps: [
      "In a pan, melt the butter over medium heat.",
      "Add sweet corn kernels to the pan and cook for 2-3 minutes, stirring occasionally.",
      "Season with salt, black pepper, and chili powder (if using). Stir well.",
      "Cook for an additional 2-3 minutes until the corn is heated through and coated with seasoning.",
      "If desired, sprinkle grated cheese over the corn and let it melt before serving.",
      "Garnish with chopped parsley or coriander, if desired, and serve hot.",
    ],
    instructions:
      "This quick and easy sweet corn recipe makes a delicious snack or side dish, with options to add cheese and herbs for extra flavor.",
    image: "sweetcorn.jpg",
  },
  {
    name: "Uddin Vada (Medu Vada)",
    ingredients: [
      "1 cup urad dal (split black gram, soaked for 4 hours)",
      "1 green chili, finely chopped",
      "1 teaspoon ginger, grated",
      "1/4 cup chopped onions",
      "1 tablespoon chopped coriander leaves",
      "Salt to taste",
      "Oil for deep frying",
    ],
    steps: [
      "Drain the soaked urad dal and grind it into a smooth, thick batter. Add minimal water to keep the batter thick.",
      "Transfer the batter to a bowl and add green chili, ginger, onions, coriander leaves, and salt. Mix well.",
      "Heat oil in a deep pan for frying.",
      "Wet your hands, take a small portion of the batter, and shape it into a round patty. Make a small hole in the center to form the vada shape.",
      "Carefully slide the vada into the hot oil and fry on medium heat until golden and crispy.",
      "Remove and drain on paper towels. Serve hot with coconut chutney or sambar.",
    ],
    instructions:
      "Crispy, savory vadas made from urad dal batter, seasoned with spices and fried until golden. A popular South Indian snack.",
    image: "medu vada.jpg",
  },
  {
    name: "Puri Bhaji",
    ingredients: [
      "2 cups whole wheat flour",
      "1/2 teaspoon salt",
      "Water for kneading",
      "Oil for deep frying",
      "2 tablespoons oil (for bhaji)",
      "1/2 teaspoon mustard seeds",
      "1/4 teaspoon turmeric powder",
      "1/2 teaspoon cumin seeds",
      "1 green chili, chopped",
      "1/2 inch ginger, grated",
      "1 medium onion, sliced",
      "3 medium potatoes, boiled and cubed",
      "Salt to taste",
      "Fresh coriander leaves for garnish",
    ],
    steps: [
      "For the puris, combine flour and salt in a bowl, gradually adding water to knead a smooth, firm dough. Let it rest for 15 minutes.",
      "Divide the dough into small balls, roll them into small circles, and deep-fry in hot oil until puffed and golden. Drain and set aside.",
      "For the bhaji, heat 2 tablespoons oil in a pan, add mustard seeds, cumin seeds, green chili, ginger, and sliced onions. Sauté until onions are soft.",
      "Add turmeric powder and mix, then add cubed potatoes and salt. Toss everything well and cook for 2-3 minutes.",
      "Garnish with fresh coriander leaves and serve hot with puris.",
    ],
    instructions:
      "A classic Indian breakfast or snack combo. Fluffy puris served with a spiced potato bhaji.",
    image: "puri bhaji.jpg",
  },
  {
    name: "Fish Fry",
    ingredients: [
      "4 fish fillets (pomfret, kingfish, or tilapia)",
      "1 tablespoon red chili powder",
      "1/2 teaspoon turmeric powder",
      "1 tablespoon lemon juice",
      "Salt to taste",
      "1/4 cup rice flour (for coating)",
      "Oil for shallow frying",
    ],
    steps: [
      "In a bowl, mix red chili powder, turmeric powder, lemon juice, and salt. Rub this marinade onto the fish fillets and let marinate for 15-20 minutes.",
      "Coat each fillet with rice flour.",
      "Heat oil in a pan and shallow fry the fish on medium heat until golden brown on both sides.",
      "Drain on paper towels and serve hot with lemon wedges and sliced onions.",
    ],
    instructions:
      "Crispy, spicy fish fillets marinated in spices and shallow fried to perfection.",
    image: "fish fry.jpg",
  },
  {
    name: "Fish Curry",
    ingredients: [
      "500 grams fish pieces (like salmon or tilapia)",
      "2 tablespoons oil",
      "1 onion, finely chopped",
      "1 tomato, chopped",
      "1 teaspoon ginger-garlic paste",
      "1/2 teaspoon turmeric powder",
      "1 teaspoon red chili powder",
      "1 teaspoon coriander powder",
      "1/2 teaspoon garam masala",
      "Salt to taste",
      "1/2 cup coconut milk",
      "Fresh coriander leaves for garnish",
    ],
    steps: [
      "Heat oil in a pan, add onions, and sauté until golden.",
      "Add ginger-garlic paste and sauté for 1-2 minutes.",
      "Add tomatoes, turmeric powder, red chili powder, coriander powder, and salt. Cook until tomatoes are soft.",
      "Add fish pieces and mix gently. Cover and cook for 5-7 minutes on low heat.",
      "Add coconut milk and simmer for a few more minutes.",
      "Garnish with coriander leaves and serve hot with rice.",
    ],
    instructions:
      "A flavorful fish curry made with coconut milk and a blend of spices, perfect with rice or chapati.",
    image: "fish curry.jpg",
  },
  {
    name: "Fish Biryani",
    ingredients: [
      "300 grams fish fillets, cut into pieces",
      "1 cup basmati rice",
      "1/2 cup yogurt",
      "1 tablespoon ginger-garlic paste",
      "1/2 teaspoon turmeric powder",
      "1 teaspoon red chili powder",
      "1/2 teaspoon garam masala",
      "Salt to taste",
      "1 onion, thinly sliced",
      "1 tomato, chopped",
      "1/2 cup chopped mint and coriander leaves",
      "2 tablespoons oil",
      "1/2 teaspoon cumin seeds",
      "2-3 whole cloves",
      "1-inch cinnamon stick",
      "2-3 green cardamom",
    ],
    steps: [
      "Marinate the fish pieces with yogurt, ginger-garlic paste, turmeric powder, red chili powder, garam masala, and salt. Let it rest for 30 minutes.",
      "Cook basmati rice until it's 70% done. Drain and set aside.",
      "Heat oil in a pan, add cumin seeds, cloves, cinnamon, and cardamom. Add sliced onions and fry until golden brown.",
      "Add tomatoes and cook until they turn soft. Add marinated fish and cook for 5-7 minutes.",
      "In a separate large pot, layer half of the rice, followed by the fish mixture, and then the remaining rice. Sprinkle chopped mint and coriander leaves.",
      "Cover and cook on low heat for 10-15 minutes.",
      "Serve hot, garnished with fried onions and raita.",
    ],
    instructions:
      "A delicious, layered fish biryani cooked with fragrant spices, perfect for a festive meal.",
    image: "fish biryani.jpg",
  },
  {
    name: "Pav Bhaji",
    ingredients: [
      "4 pav buns",
      "2 tablespoons butter",
      "1 onion, finely chopped",
      "1 capsicum, finely chopped",
      "1/2 cup peas",
      "1/2 cup cauliflower, chopped",
      "1 carrot, chopped",
      "2 potatoes, boiled and mashed",
      "2 tomatoes, chopped",
      "1 tablespoon ginger-garlic paste",
      "1 teaspoon red chili powder",
      "1 teaspoon pav bhaji masala",
      "Salt to taste",
      "Fresh coriander leaves for garnish",
      "Lemon wedges for serving",
    ],
    steps: [
      "In a pot, add butter, onions, and capsicum. Sauté until onions are golden brown.",
      "Add ginger-garlic paste, peas, cauliflower, carrot, potatoes, and tomatoes. Sauté for 2-3 minutes.",
      "Add red chili powder, pav bhaji masala, and salt. Mash everything together with a potato masher.",
      "Add water to adjust consistency and simmer until the vegetables are fully cooked and soft.",
      "Toast pav buns with a little butter on a skillet.",
      "Serve bhaji with toasted pav, garnished with fresh coriander leaves and a side of lemon wedges.",
    ],
    instructions:
      "A popular Indian street food, pav bhaji is a flavorful mashed vegetable dish served with buttered pav buns.",
    image: "pav bhaji.jpg",
  },
  {
    name: "Pulav",
    ingredients: [
      "1 cup basmati rice",
      "1 tablespoon oil or ghee",
      "1 teaspoon cumin seeds",
      "1 bay leaf",
      "2-3 cloves",
      "1 cinnamon stick",
      "1 onion, sliced",
      "1/2 cup mixed vegetables (carrot, peas, beans, etc.)",
      "1 teaspoon garam masala",
      "Salt to taste",
      "2 cups water",
      "Fresh coriander leaves for garnish",
    ],
    steps: [
      "Rinse the basmati rice and soak it for 15-20 minutes, then drain.",
      "In a pot, heat oil or ghee. Add cumin seeds, bay leaf, cloves, and cinnamon stick.",
      "Add sliced onions and sauté until golden brown.",
      "Add mixed vegetables and cook for a few minutes.",
      "Add the rice, garam masala, and salt. Stir to mix everything well.",
      "Add water, cover, and cook on low heat until the rice is fully cooked and fluffy.",
      "Garnish with fresh coriander leaves and serve hot.",
    ],
    instructions:
      "A fragrant rice dish cooked with spices and vegetables, perfect for a quick, flavorful meal.",
    image: "pulav.jpg",
  },
  {
    name: "Green Moong Dal Kheer",
    ingredients: [
      "1/2 cup green moong dal (split or whole green gram, soaked for 2 hours)",
      "1 liter milk",
      "1/2 cup sugar",
      "1/4 teaspoon cardamom powder",
      "2 tablespoons chopped almonds and cashews",
      "2 tablespoons raisins",
      "1 tablespoon ghee",
      "A pinch of saffron strands (optional)",
    ],
    steps: [
      "Drain the soaked green moong dal.",
      "Heat ghee in a pan and add the green moong dal. Roast on low heat until it turns golden and aromatic.",
      "In a separate pot, bring the milk to a boil, then add the roasted dal.",
      "Cook on low heat, stirring frequently, until the dal softens and the milk thickens (about 20-30 minutes).",
      "Add sugar, cardamom powder, and saffron strands (if using), and stir well.",
      "Add chopped almonds, cashews, and raisins. Continue cooking for a few more minutes.",
      "Remove from heat and let it cool slightly before serving. Serve warm or chilled.",
    ],
    instructions:
      "A creamy, rich Indian dessert made with green moong dal, milk, and aromatic spices. Perfect for festive occasions or as a unique dessert option.",
    image: "green moong kheer.jpg",
  },
];
